### ISSUE TITLE
FEATURE REQUEST: Use Docker socket instead of port

### ISSUE THREAD

**Issue by adamdabbracci** [hystax/optscale#1]
The line in `runkube.py` that creates a Docker client expects the daemon to be exposed on a local TCP port:

```
cl = DockerClient(base_url='tcp://{0}:{1}'.format(node, self.dport))
```

However, the default on most operating systems is a socket, and exposing the TCP port is advanced. This can be addressed by simply referencing the socket address instead:

```
cl = DockerClient(base_url='unix://var/run/docker.sock')
```

Ideally, it would check for both and use the first one it finds.

**Comment by nexusriot** [comment]
could you please try following, looks like this is what you are looking for
```
./runkube.py --use-socket --with-elk  -o overlay/user_template.yml -- <deployment name> component_versions.yaml
```

**Comment by maxb-hystax** [comment]
@adamdabbracci we've checked deployment with --use-socket internally, it works. 
Please check from your side and let us know, thanks!
