### ISSUE TITLE
OIDC Support in optscale

### ISSUE THREAD

**Issue by mousumi16** [hystax/optscale#11]
Hi @maxb-hystax 

Do you have support to integrate optscal with keycloak , okta etc. ?
PLease let me know the config files for that.

Thanks
Mousumi

**Comment by maxb-hystax** [comment]
Hi @mousumi16 

OptScale doesn't have authorization support for keycloak and okta at this time.
It supports password-based, Google, and Microsoft login types.

Planning to add some SSO providers this year.

**Comment by dotalchemy** [comment]
@maxb-hystax - are you still targeting an 02/23 update to this repo with pipelines / helm?

I've been holding off adding SSO provider support hoping that disposable dev environments might be a little easier and didn't want to spend the time building my own if there were pipelines on the way.

**Comment by maxb-hystax** [comment]
OptScale is fully buildable now and open for contributions with new SSO providers.
