### ISSUE TITLE
SMTP bad UTF-8 syntax

### ISSUE THREAD

**Issue by elikkatzgit** [hystax/optscale#116]
When inviting a new user, an email is being sent but rejected by the mail server.

Setting in the user_template.yml:
# SMTP server and credentials used for sending emails
smtp:
  server: mailx1.example.com
  email: example@example.com
  port: 25
  #password:
 
Response from the mail server:
500 5.5.2 Error: bad UTF-8 syntax

While taking a PCAP, I noticed that the request coming from the optscale server looks wired (see attachment)

Running on AWS instance, Ubuntu 20.04.6 LTS
![optscale-smtp](https://github.com/hystax/optscale/assets/50174655/32a8c2ed-ac7b-4a6c-b694-9b9f946a6049)

**Comment by maxb-hystax** [comment]
OptScale module for sending emails requires SMTP SSL protocol to be used, see https://github.com/hystax/optscale/blob/ce6af28c68200e47a9d462a048c85bda85315ff6/herald/modules/email_sender/sender.py#L45
Please try and let us know, thanks!

**Comment by elikkatzgit** [comment]
Hi, thank you, I managed to integrate with SMTP-SSL and managed to have server hello and client hello, cipher handskae, application data and all...
yet I'm getting a SMPT error Alert Message: Encrypted Alert

AS this is encrypted now, I cannot tell what is the issue.
Where in the optsclae, I can track the logs of the SNMP logic to see what the issue?
