### ISSUE TITLE
Container

### ISSUE THREAD

**Issue by Upasana1000** [hystax/optscale#12]
Can you please tell me, in which container are all the images saved? Cause when i am trying to do some changes in my repository, its not reflecting.

**Comment by maxb-hystax** [comment]
Hi! The images which are used for the deployment are prebuilt ones, available on DockerHub - https://hub.docker.com/u/hystax
We are working on publishing image build scripts, aiming for March-April delivery.
At the moment, for the most of the services (except NGUI - OptScale portal) you can upload your changes directly to running containers, then commit the image and rescale corresponding  service.
If you want to make changes in NGUI - you can build it from Dockerfile - https://github.com/hystax/optscale/blob/integration/ngui/Dockerfile
