### ISSUE TITLE
Unble to get the Pods running

### ISSUE THREAD

**Issue by kartraj** [hystax/optscale#123]
we are trying to bring up this setting on AWS VM.  please advise!

After we  install the Kubs cluters we see that the Pods are not coming up properly.
**ubuntu@ip-172-31-92-122:~$ kubectl get pod
NAME                                                            READY   STATUS    RESTARTS   AGE
etcd-operator-etcd-operator-etcd-operator-5c8d485cfb-k76d2      1/1     Running   0          76s
initial-config-nginx-ingress-controller-x2j4f                   0/1     Pending   0          84s
initial-config-nginx-ingress-default-backend-5df46cc4d9-dwjd7   1/1     Running   0          84s
ngingress-nginx-ingress-controller-5rd5t                        1/1     Running   0          104s
ngingress-nginx-ingress-default-backend-7cf5b8d7f4-jktgn        1/1     Running   0          104s**

when we try to run the cluster setting we get the below error.
please confirm if the deployment name and version is acceptable
**runkube.py --with-elk  -o overlay/user_template.yml -- dzopscale 3.4.3-0**  

ubuntu@ip-172-31-92-122:~/optscale/optscale-deploy$ python3 runkube.py --with-elk  -o overlay/user_template.yml -- dzopscale 3.4.3-0
18:19:48.680: Pulling images for 172.31.92.122
18:19:48.694: Pulling image index.docker.io/hystax/arcee with tag 3.4.3-0
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.8/dist-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://172.31.92.122:2376/v1.40/images/create?tag=3.4.3-0&fromImage=index.docker.io%2Fhystax%2Farcee

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "runkube.py", line 430, in <module>
    acr.start(args.check, args.update_only)
  File "runkube.py", line 307, in start
    self.pull_images(node)
  File "runkube.py", line 153, in pull_images
    self._pull_image(
  File "runkube.py", line 128, in _pull_image
    image = docker_cl.images.pull(**params)
  File "/usr/local/lib/python3.8/dist-packages/docker/models/images.py", line 465, in pull
    pull_log = self.client.api.pull(
  File "/usr/local/lib/python3.8/dist-packages/docker/api/image.py", line 429, in pull
    self._raise_for_status(response)
  File "/usr/local/lib/python3.8/dist-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e) from e
  **File "/usr/local/lib/python3.8/dist-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation) from e
docker.errors.NotFound: 404 Client Error for http://172.31.92.122:2376/v1.40/images/create?tag=3.4.3-0&fromImage=index.docker.io%2Fhystax%2Farcee: Not Found ("manifest for hystax/arcee:3.4.3-0 not found: manifest unknown: manifest unknown")**

**Comment by kartraj** [comment]
ubuntu@ip-172-31-92-122:~/optscale/optscale-deploy$ kubectl get services
NAME                                           TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)                      AGE
etcd-restore-operator                          ClusterIP      10.99.125.21     <none>        19999/TCP                    13m
initial-config-nginx-ingress-controller        LoadBalancer   10.106.221.133   <pending>     443:19048/TCP                13m
initial-config-nginx-ingress-default-backend   ClusterIP      10.96.181.22     <none>        80/TCP                       13m
kubernetes                                     ClusterIP      10.96.0.1        <none>        443/TCP                      14m
ngingress-nginx-ingress-controller             LoadBalancer   10.106.75.177    <pending>     80:26445/TCP,443:27427/TCP   13m
ngingress-nginx-ingress-default-backend        ClusterIP      10.105.201.132   <none>        80/TCP                       13m

i think the pod is having port conflict. Please help us identify issue

**Comment by nexusriot** [comment]
please use https://github.com/hystax/optscale/releases/tag/2023091300-public-pre-release for deployment

**Comment by kartraj** [comment]
![MicrosoftTeams-image (3)](https://github.com/hystax/optscale/assets/57901779/d79a9f4c-ef24-4750-98e5-3fac3d380ab6)
when we use the 2023091300-public-pre-release we still get the error manifest not found,

the 2023091300-public tag worked and the images are getting downloaded. But the process fails with the permission issue on /tmp? 

![MicrosoftTeams-image (4)](https://github.com/hystax/optscale/assets/57901779/b560740e-195e-4082-a702-1de2e05d649f)


Can you please guide?

**Comment by maxb-hystax** [comment]
Please checkout https://github.com/hystax/optscale/releases/tag/2023091300-public-pre-release and use deployment from that commit.

**Comment by kartraj** [comment]
When we check out from the  public -pre-release it fails to run the runkube.py 
(.venv) ubuntu@ip-172-31-32-229:~/optscale-new/optscale-2023091300-public-pre-release/optscale-deploy$ ./runkube.py --with-elk  -o overlay/user_template.yml -- dzoptscale 2023091300-public-pre-release
08:10:17.983: Pulling images for 172.31.32.229
Traceback (most recent call last):
  File "./runkube.py", line 402, in <module>
    acr.start(args.check, args.update_only)
  File "./runkube.py", line 284, in start
    self.pull_images(node)
  File "./runkube.py", line 132, in pull_images
    for image, tag in self.versions_info['images'].items():
  File "./runkube.py", line 108, in versions_info
    with open(self.component_versions) as f_ver:
FileNotFoundError: [Errno 2] No such file or directory: '2023091300-public-pre-release'


The same with the 2023091300-public also.  



So, I went to the integration branch and ran the Runkube.py  and release 2023091300-public and was able to get the images going, but when we tried to connect it said

![MicrosoftTeams-image (6)](https://github.com/hystax/optscale/assets/57901779/98476905-5a93-448e-a0d6-e97bc2236b7c)


How do we access the log files of the Ngnix pod?
![MicrosoftTeams-image (7)](https://github.com/hystax/optscale/assets/57901779/800a7605-1e4c-487a-aba5-1bbbaf738e68)
![MicrosoftTeams-image (8)](https://github.com/hystax/optscale/assets/57901779/abf9b5bc-c746-42e8-91b1-858fefae0349)

**Comment by nk-hystax** [comment]
@kartraj have you set the value for `react_app_google_oauth_client_id` in overlay/user_template.yml?

**Comment by kartraj** [comment]
@nk-hystax  thank you for that nudge. it really helped. but now I think we hit another error while connecting our Cloud accounts. any suggestions on this?
![MicrosoftTeams-image (9)](https://github.com/hystax/optscale/assets/57901779/e75507a4-410b-4719-9c52-69b41eb63d60)

we have AWS accounts giving the currency in $ while Azure and GCP in INR.
do we need a separate org for each cloud? what is your advice? 
![MicrosoftTeams-image (10)](https://github.com/hystax/optscale/assets/57901779/2c4eb3a8-8e5c-4115-9abe-c04729ca840f)

@maxb-hystax @nexusriot

**Comment by maxb-hystax** [comment]
Hi @kartraj!

At the moment, you need to create separate organization for each currency you use. Organization's currency can be changed before connection of the first cloud account.

**Comment by kiranRadhh** [comment]
Hi @maxb-hystax

We are still facing an issue with google oauth login. Please find the ss below.
What should the redirect URL set to in the google oauth settings ?

![Screenshot 2023-09-28 190218](https://github.com/hystax/optscale/assets/139243190/e6091b9d-ac50-41e0-b337-529806d9e437)
