### ISSUE TITLE
Alibaba China Regions Support for demo 

### ISSUE THREAD

**Issue by cj6pilotcn** [hystax/optscale#125]
**Describe the bug**
Hello, team. I tried to integrate an AK/SK from Alibaba China region. But the status of data source always indicates "Billing import failed" "AttachedInstanceId".

**To Reproduce**
1. Go to 'my.optscale.com'
2. Click on 'the menu of data sources' and click "add" button to add an Alibaba Cloud. 
3. Input AK/SK with read-only permissions and click "connect"
4. See "Billing import failed" "AttachedInstanceId".

**Expected behavior**
Accounts from Alibaba Cloud China regions can be integrated correctly.
 
**Screenshots**
<img width="1154" alt="截屏2023-09-19 11 01 31" src="https://github.com/hystax/optscale/assets/87694151/a3539819-b5bb-4c47-a6c4-42b0617cc38c">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version [116.0.5845.187]

**Comment by v-hx** [comment]
@cj6pilotcn , the issue with problematic regions has been resolved. The fix is already available. If this is still relevant for you, please give it a try once again.
