### ISSUE TITLE
How install optscale?

### ISSUE THREAD

**Issue by KelvinFerraz** [hystax/optscale#13]
Hello everyone!

I try to find some documentation on "how to install", but I didn't find it. I want to test in my environment (EC2 Instance for example).

Someone can help me in this case?

Thanks

**Comment by maxb-hystax** [comment]
Hi! You can find it here - https://github.com/hystax/optscale/blob/integration/optscale-deploy/README.md

**Comment by KelvinFerraz** [comment]
Hi @maxb-hystax, thank  you for reply.

So I tried use this documentation, but how do I start the service?

This documentation explain how to install, but I don't know how start the service running on EC2.

Regards.

**Comment by rajeshkarka** [comment]
> Hi! You can find it here - https://github.com/hystax/optscale/blob/integration/optscale-deploy/README.md

@maxb-hystax we are also facing same issue, seems like some pods are running but there is no documentation to get it render ui or dashboard part. 
Thanks in Advance.
