### ISSUE TITLE
Disable assignment rule condition delete button if only one condition left

### ISSUE THREAD

**Issue by maxb-hystax** [hystax/optscale#130]
**Steps to reproduce**

1. Go to the add/edit rule page
3. Make sure there is one line left with the conditions
4. Press delete button

**Actual result**

The delete button is clickable, but no actual action occurs.

**Expected result**

The delete button becomes inactive when the last line with conditions remains.

**Comment by gpuligundla** [comment]
Hi @maxb-hystax, can i work on this issue :)

**Comment by maxb-hystax** [comment]
@gpuligundla sure, you are welcome!

**Comment by Lasterminator** [comment]
I would like to work on it
