### ISSUE TITLE
Generate .htpasswd files based on env vars

### ISSUE THREAD

**Issue by maxb-hystax** [hystax/optscale#132]
Initiated by comment https://github.com/hystax/optscale/pull/109#discussion_r1314837110

Several components have .htpasswd authentication which can only be changed during images build:
- docker_images/elk
- docker_images/grafana_nginx

It will be better to add init script to their images which checks if container has HTPASSWD_USER and HTPASSWD_PASS environment vars, generates .htpasswd and passes launch to component launcher. These env vars can be set in deployment config - https://github.com/hystax/optscale/blob/integration/optscale-deploy/overlay/user_template.yml and used for launching corresponding services similarly to https://github.com/hystax/optscale/blob/integration/optscale-deploy/optscale/templates/ngui.yaml

**Comment by sd-hystax** [comment]
fixed in [bf053c4a8ff81070c725669b5cd5c5b419071c40](https://github.com/hystax/optscale/commit/bf053c4a8ff81070c725669b5cd5c5b419071c40)
