### ISSUE TITLE
Please explain ./runkube.py --with-elk  -o overlay/user_template.yml -- <deployment name> <version>

### ISSUE THREAD

**Issue by deepakpal-in** [hystax/optscale#135]
**Describe the bug**
where is the <version> which is required to pass as argument to below command in the README.md

./runkube.py --with-elk  -o overlay/user_template.yml -- <deployment name> <version>

earlier there was component_versions.yaml file under optscale directory but that is also not there . please explain how to provide version to runkube.py under this command.

**To Reproduce**

./runkube.py --with-elk  -o overlay/user_template.yml -- <deployment name> <version>

**Expected behavior**
optscale successful installation

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04

**Comment by nexusriot** [comment]
the current version will work with this
```
./runkube.py --use-socket --with-elk  -o overlay/user_template.yml -- <deployment name> <version>
```
```
./runkube.py --use-socket --with-elk  -o overlay/user_template.yml -- my-deployment 2023092701-public
```

you can take version number from [here](https://github.com/hystax/optscale/releases)

**Comment by deepakpal-in** [comment]
Thanks for the information @nexusriot ,

1)  for the  overlay/user_template.yml, I just want to use this to access AWS so can I just provide AWS access and secret key and left everything else as it is ?

https://github.com/hystax/optscale/blob/bc760992e08db2db6bdf0356a622423f7334050b/optscale-deploy/overlay/user_template.yml#L10

2) How I will get the cluster secret mentioned in runkube.py
https://github.com/hystax/optscale/blob/bc760992e08db2db6bdf0356a622423f7334050b/optscale-deploy/overlay/user_template.yml#L4

**Comment by deepakpal-in** [comment]
@nexusriot , is there is any update on this. Or any better installation document available?

**Comment by nexusriot** [comment]
1. yes
2. I suggest to use Python3 to generate UUIDs
```
vlad@vlad-gmk:~$ python3
Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import uuid
>>> uuid.uuid4()
UUID('8b000e26-91a9-4794-90ae-4839730bc8c0')

```
