### ISSUE TITLE
AWS account Cost forecast is not looking right @ root and linked account levels

### ISSUE THREAD

**Issue by kartraj** [hystax/optscale#142]
We have connected the AWS root account enabled with also linked one of its child accounts under it as datasources. The forecast is showing ~$30 at the root level but at the linked account level has a forecast of ~$80.
<img width="1139" alt="Screenshot 2023-10-03 at 8 38 50 PM" src="https://github.com/hystax/optscale/assets/57901779/148b94da-f94f-411f-9fd4-b07272627c1c">

what could be the reason? please advise @maxb-hystax  @sd-hystax

**Comment by maxb-hystax** [comment]
Hi @kartraj, OptScale counts expenses for both accounts separately, meaning that root account expenses track only expenses for resources which belong to the root account itself. Could this be the reason for confusion you see?
