### ISSUE TITLE
Run OptScale locally

### ISSUE THREAD

**Issue by claudioscheer** [hystax/optscale#145]
Hello!

I was hoping to run the project locally and make some modifications to ngui for my tests. Could you guide me on how to execute `ngui/server` and `ngui/ui` on my end? I noticed `ngui/server/.env` requires UI_BUILD_PATH and PROXY_URL, and I'm uncertain about the appropriate values. Similarly, I'm unsure about the REACT_APP_PROXY in `ngui/ui/.env`.

I was able to build docker images on my end. Just not sure about the steps required to run the project locally.

Any assistance would be greatly appreciated.

**Comment by ek-hystax** [comment]
Hello!

To run the project locally in development mode follow these steps:
1. Navigate to `ui` directory: `cd ngui/ui`.
4. Install dependencies using `npm ci` (make sure you have `npm` and `node` installed, we are currently using `node@v18.12.1` and `npm@8.19.2`) 
5. Define environment variables in the `.env` file.
   I believe for `REACT_APP_PROXY` you could use the same ip as in the following instruction:
   `ansible-playbook -e "ansible_ssh_user=<user>" -k -K -i "<ip address>," ansible/k8s-master.yaml`
   (https://github.com/hystax/optscale#kubernetes-installation)
   e.g `REACT_APP_PROXY = "https://xxx.xxx.xxx.xxx"`
6. Start the project with `npm start`

If you want to run in the production build follow these:
1. Navigate to the `ui` directory: `cd ngui/ui`
3. Install dependencies: `npm ci` 
4. Define environment variables in the `.env` file (see above)
5. Build the project: `npm run build`
7. Get the `build` folder path, e.g `/home/user/optscale/ngui/ui`(the `/build` will be added automatically)
8. Navigate to the `server` directory `cd ngui/server`
9. Install dependencies: `npm ci`
10. Define environment variables in the `.env` file
   `UI_BUILD_PATH="/home/user/optscale/ngui/ui"`
   `PROXY_URL=<same value as for REACT_APP_PROXY>`
11. Run the server: `npm start`

Hope this helps!

**Comment by claudioscheer** [comment]
Excellent! This helped a lot. Thanks, @ek-hystax.

**Comment by Shubhagj** [comment]
Hello!

I'm running ngui/server and ngui/ui on my end. I've noticed that ngui/server/.env requires UI_BUILD_PATH and PROXY_URL, and I'm uncertain about the appropriate values. Similarly, I'm unsure about REACT_APP_PROXY in ngui/ui/.env. However, I've provided proxy URL=http://localhost:4000/ in both the UI (running on port 3000) and the server side (running on port 4000). Despite this, when I try to sign up, and creating an organization I encounter a proxy error.

On the server side, the error message is:
[HPM] Error occurred while proxying request localhost:4000/restapi/v2/organizations to http://localhost:4000/
[ENOBUFS] (https://nodejs.org/api/errors.html#errors_common_system_errors)

And on the UI side, the error message is:
[HPM] Error occurred while proxying request localhost:3000/restapi/v2/organizations to http://localhost:3000/
[ENOBUFS] (https://nodejs.org/api/errors.html#errors_common_system_errors)

I would greatly appreciate any assistance with resolving this issue.

**Comment by ek-hystax** [comment]
> Hello!
> 
> I'm running ngui/server and ngui/ui on my end. I've noticed that ngui/server/.env requires UI_BUILD_PATH and PROXY_URL, and I'm uncertain about the appropriate values. Similarly, I'm unsure about REACT_APP_PROXY in ngui/ui/.env. However, I've provided proxy URL=http://localhost:4000/ in both the UI (running on port 3000) and the server side (running on port 4000). Despite this, when I try to sign up, and creating an organization I encounter a proxy error.
> 
> On the server side, the error message is: [HPM] Error occurred while proxying request localhost:4000/restapi/v2/organizations to http://localhost:4000/ [ENOBUFS] (https://nodejs.org/api/errors.html#errors_common_system_errors)
> 
> And on the UI side, the error message is: [HPM] Error occurred while proxying request localhost:3000/restapi/v2/organizations to http://localhost:3000/ [ENOBUFS] (https://nodejs.org/api/errors.html#errors_common_system_errors)
> 
> I would greatly appreciate any assistance with resolving this issue.

Hello @Shubhagj,

Regarding the PROXY_URL for ngui/server and VITE_PROXY for ngui/ui, these are URLs pointing to a server where OptScale is deployed. For instance, you could set VITE_PROXY as https://xxx.xxx.xxx.xxx or https://my-host-name.com if you have DNS configured.

To find the appropriate IP address for VITE_PROXY (or PROXY_URL), you can use the same IP address as provided in the following instruction:

```bash
ansible-playbook -e "ansible_ssh_user=<user>" -k -K -i "<ip address>," ansible/k8s-master.yaml
```
You can refer to the installation guide [here](https://github.com/hystax/optscale?tab=readme-ov-file#getting-started) for more details.
