### ISSUE TITLE
SMTP integration

### ISSUE THREAD

**Issue by elikkatzgit** [hystax/optscale#147]
With continue to https://github.com/hystax/optscale/issues/116 

Hi, thank you, I managed to integrate with SMTP-SSL and managed to have server hello and client hello, cipher handskae, application data and all...
yet I'm getting a SMPT error Alert Message: Encrypted Alert

AS this is encrypted now, I cannot tell what is the issue.
Where in the optsclae, I can track the logs of the SNMP logic to see what the issue?

**Comment by maxb-hystax** [comment]
Hi @elikkatzgit 
Please check Herald service logs (container_name:*herald*)in Kibana (port 30081) - they should describe what's happening there.

**Comment by devops-cybersapient** [comment]
how to get the credentials for kibana.its asking for creds while accessing the port
