### ISSUE TITLE
Some files are missing

### ISSUE THREAD

**Issue by rakesh-infolob** [hystax/optscale#15]
I am unable to edit the files and build docker image due to missing files.
In NGUI, .env, scripts/prune_node_modules.sh are missing
In rest-api, to pull pip libraries http://pypi.dts.loc:8080/pip/ is not working, rest_api_server/recommendation_cleanup_scripts file is missing, live_demo.json is missing
and many more...

**Comment by maxb-hystax** [comment]
Hi Rakesh,
The build scripts for the services, as well as are planned for the end of March-beginning of April.

**Comment by tguisep** [comment]
Any update on that part ?
I wanted to make some modification to the AWS cloud provider (pricing).
It would be manageable to do without but if you plan to release a working/build-able version, it would be nice.

**Comment by rogdex24** [comment]
> Any update on that part ? I wanted to make some modification to the AWS cloud provider (pricing). It would be manageable to do without but if you plan to release a working/build-able version, it would be nice.

Did you find any solution? How do I implement the changes on the container and run them?

**Comment by tguisep** [comment]
I found an other way, without modifying.
I was thinking to extract the container (missing file are available inside) & rebuild-it with my modification.

**Comment by rogdex24** [comment]
> I found an other way, without modifying. I was thinking to extract the container (missing file are available inside) & rebuild-it with my modification.

yeah but that's a long process as one package / file has many dependencies, and how to build the images? the scripts are incomplete afaik

**Comment by maxb-hystax** [comment]
Released fully buildable source, please try!
https://github.com/hystax/optscale/releases/tag/2023092001-public

**Comment by rogdex24** [comment]
How do I use the local docker images instead pulling from your docker registry ? @maxb-hystax

**Comment by nexusriot** [comment]
firstly build images with tag local
```
./build.sh
```
then run runkube.py with **_--no-pull_** argument
```
./runkube.py --with-elk  --no-pull -- <deployment name>  <version>
```
