### ISSUE TITLE
Add environment locked 

### ISSUE THREAD

**Issue by tguisep** [hystax/optscale#159]
Hello,

Any good reason to not allow more environments ?

https://github.com/hystax/optscale/blob/integration/rest_api/rest_api_server/handlers/v2/cloud_account.py#L123-L124

I mean, if I change this code, do I need to expect issues ?

Thomas.

**Comment by maxb-hystax** [comment]
Hi Thomas,

Environment cloud account is designed to be a single one at the moment. You can trace the logic starting from here - https://github.com/hystax/optscale/blob/6f7b64c7d8c57dee5793aa0d2b46241be1c7f7ca/rest_api/rest_api_server/controllers/environment_resource.py#L75C1-L75C1

**Comment by tguisep** [comment]
Ok, thanks.

Well, I ll not touch it at the moment :)
