### ISSUE TITLE
docker version not found issue

### ISSUE THREAD

**Issue by krm731** [hystax/optscale#17]
TASK [common : Install docker-ce] ********************************************************************************************************************************************************************
fatal: [172.31.29.83]: FAILED! => {"cache_update_time": 1677632144, "cache_updated": true, "changed": false, "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"      install 'docker-ce=5:19.03.*'' failed: E: Version '5:19.03.*' for 'docker-ce' was not found\n", "rc": 100, "stderr": "E: Version '5:19.03.*' for 'docker-ce' was not found\n", "stderr_lines": ["E: Version '5:19.03.*' for 'docker-ce' was not found"], "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\nPackage docker-ce is not available, but is referred to by another package.\nThis may mean that the package is missing, has been obsoleted, or\nis only available from another source\nHowever the following packages replace it:\n  docker-ce-cli\n\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information...", "Package docker-ce is not available, but is referred to by another package.", "This may mean that the package is missing, has been obsoleted, or", "is only available from another source", "However the following packages replace it:", "  docker-ce-cli", ""]}

PLAY RECAP *******************************************************************************************************************************************************************************************
172.31.29.83               : ok=10   changed=5    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

**Comment by maxb-hystax** [comment]
Please let us know the OS version on which you are trying to deploy.

**Comment by romsworld** [comment]
Hi,
I have same pb with debian 11.
Linux NC-Komiser 5.10.0-11-amd64 #1 SMP Debian 5.10.92-1 (2022-01-18) x86_64 GNU/Linux

TASK [common : Add docker repo] ***********************************************************************************************************************
fatal: [172.20.93.13]: FAILED! => {"changed": false, "msg": "apt cache update failed"}

PLAY RECAP ********************************************************************************************************************************************
172.20.93.13               :ok=9changed=4 unreachable=0failed=1 skipped=0    rescued=0    ignored=0

**Comment by nexusriot** [comment]
It looks like you're using Debian.
Currently we full support support only for Ubuntu 20.04. Planning to extend supported OS.
