### ISSUE TITLE
[Feature request] RI/EC2 SP/Compute SP API pricing

### ISSUE THREAD

**Issue by tguisep** [hystax/optscale#170]
Hello,

I couldn't find a way to get RI/EC2 SP/Compute SP API pricing for EC2.
Insider Api do not give the values, or I missed it ?

Today, I'm using an external data source to get it  (https://instances.vantage.sh/pricing_{region}.json + home made parser). 
It works, but it's not optimal.

Would be better to have the possibility to get value directly from Optscale API.

Thomas.

**Comment by maxb-hystax** [comment]
Hi Thomas,

Correct, at the moment Insider doesn't collect RI/SP pricings.
OptScale works only with RI/SP through billing reports and then use that info for showing RI/SP utilization stats. See https://github.com/hystax/optscale/blob/integration/risp/risp_worker/worker.py for the details of this processing.

**Comment by maxb-hystax** [comment]
We'll explore the possibility to grab it to Insider as well. Do you have a use case for that?

**Comment by tguisep** [comment]
We are using intensively the API, to compute our own stats, recommandation (...).
And RI/SP pricing is one of the top needs, specifically to compute forecast usage with xx value on yy instance with EC2 SP.
