### ISSUE TITLE
Connect to GCP data source

### ISSUE THREAD

**Issue by phamngocsonls** [hystax/optscale#19]
Hi, I want to connect GCP data source follow your docs: https://hystax.com/documentation/optscale/e2e_guides/e2e_gcp.html
I have some question:
- I have 1 ORG with about 100 project and 1 billing project . With service account, what project should I create SA?
I saw SA have some compute roles, if i create SA in billing project, how SA can view compute data in other project?
- I think I should deploy self hosted VM at billing project and provite SA role at ORG level?

**Comment by maxb-hystax** [comment]
At the moment, each project requires the separate billing export. Further improvements are coming later.
