### ISSUE TITLE
Slack Integration fails with redirect_uri did not match any configured URIs

### ISSUE THREAD

**Issue by Shikhar-Nahar** [hystax/optscale#204]
**Describe the bug**
When trying to integrate the optscale deployment with slack, the "Add to slack" integration fails with redirect_uri being empty.

**To Reproduce**
1. Add proper entries for slack in user_template.yaml in overlays
```
slacker:
  slack_signing_secret: 
  slack_client_id:
  slack_client_secret:
```

2. restart the deployment
3. try to integrate with slack by clicking "Add to slack"

**Expected behavior**
Integration should go through fine.

**Screenshots**
<img width="564" alt="image" src="https://github.com/hystax/optscale/assets/19330458/dce16e5d-ba9a-4165-be24-e20d20694238">

**Desktop (please complete the following information):**
 - OS: ubuntu 20
 - Browser chrome
 - Version : 120.0.xxx

**Comment by Shikhar-Nahar** [comment]
Ok I was able to pass that step after adding the url to redirect url in slack app's "OAuth & Permissions"
I am closing this

**Comment by Shikhar-Nahar** [comment]
Ok reopening as I am now hitting an error after redirection from slack.
"This resource requires authorisation".

<img width="463" alt="image" src="https://github.com/hystax/optscale/assets/19330458/855b5173-747c-42d5-87ab-9a0e2c665722">

**Comment by tm-hystax** [comment]
Hello!

You can follow this instructions to configure your Slack application:

1) Go to https://api.slack.com/apps to create new slack app, paste app name and choose Development Slack Workspace

2) In "OAuth & Permissions" tab in "Redirect URLs" need to paste local cluster oauth_redirect slacker URL to  "https://<cluster_ip>/slacker/v2/oauth_redirect", here in "Scopes" in "Bot Token Scopes" add types of scopes (chat:write, im:history, chat:write.public, groups:write, channels:read, groups:read)

3) In "Interactivity & Shortcuts" tab enable "Interactivity", add local cluster event slacker URL to "https://<cluster_ip>/slacker/v2/events". 

**NOTE: Update user_template.yml overlay with "Client ID", "Client Secret", "Signing Secret" values from "Basic Information" tab in "App Credentials". Update your cluster with new overlay.**

4) In "Event Subscriptions" tab "Enable Events", add local cluster event slacker URL to "https://<cluster_ip>/slacker/v2/events", here in "Subscribe to bot events" add three types of events: app_home_opened, message.im, member_joined_channel

5) In "App Home" tab need to disable "Home Tab", enable "Messages Tab". In "Messages Tab" select the checkbox "Allow users to send Slash commands and messages from the messages tab".

**Comment by Shikhar-Nahar** [comment]
@tm-hystax Thanks for the quick response. I have updated the slack app settings as per your steps 
**_(Except for step-4 since the cluster is running in internal VPN and slack is unable to verify the url)_** - Is this mandatory for slack integration?

Skipping step(4), I have re-installed the slack app in the workspace.
Now when I try to connect from optscale I get the below error.
<img width="732" alt="image" src="https://github.com/hystax/optscale/assets/19330458/6ad50392-e448-43ed-8ef4-07c47635f112">

Also sharing slacker container logging output from kibana.
<img width="1463" alt="image" src="https://github.com/hystax/optscale/assets/19330458/b6e3db3d-6ca6-4c6f-b7b5-9f29ae6e1270">

**Comment by maxb-hystax** [comment]
Thank you for the description. We're taking a look what can be wrong there.

**Comment by nk-hystax** [comment]
Found and fixed the bug. The fix will be released this week, please wait for updates.

**Comment by Shikhar-Nahar** [comment]
@nk-hystax thanks, please do share the PR (commit) if the fix is pushed.

**Comment by maxb-hystax** [comment]
Fix will be delivered with the commit https://github.com/hystax/optscale/commit/0896c34c280f48bcea8e1e8dc0465440157eb6be today, and will be released to official images later this week.

**Comment by maxb-hystax** [comment]
Released in https://github.com/hystax/optscale/releases/tag/2024020701-public

**Comment by maxb-hystax** [comment]
Added instruction for Slack connection preparation https://github.com/hystax/optscale/blob/integration/slacker/README.md
