### ISSUE TITLE
User Management / Invite User Select List has to be ordered or filtered

### ISSUE THREAD

**Issue by aswintyv** [hystax/optscale#207]
**Is your feature request related to a problem? Please describe.**
When I'm inviting a user, the select list is jumbled, and not arranged. it does not have any filters. So, It's becoming hard to find the entry that I want to point to. As the size goes, it is becoming harder. There might be other places where such a functionality is taking place.

**Describe the solution you'd like**
Select list should have the ability to filter, and should be sorted alphabetically by default (Example Implementation: https://react-select.com/home)

**Describe alternatives you've considered**
The alternative is just to skim the entire list and figure out what to get.

**Additional context**

![image](https://github.com/hystax/optscale/assets/264966/3476d230-9037-46e3-87ba-7b2c69b73d41)

**Comment by v-hx** [comment]
@aswintyv , thank you for pointing this out. We've taken this into work, and will improve the experience in the upcoming release.

**Comment by maxb-hystax** [comment]
Hi, we've improved the selector here:
![image](https://github.com/hystax/optscale/assets/24920606/1f007172-671f-4496-aba5-7832f37a7928)
Commit https://github.com/hystax/optscale/commit/fc1c9765fdbf72d15b2d0dac0fc4e25f8f7c9825
Will be included into release images on the next week
