### ISSUE TITLE
Connecting an AWS account without static IAM user

### ISSUE THREAD

**Issue by pawelh-dbs** [hystax/optscale#21]
Hello,

I've deployed OptScale and now want to add a data source, but my company has a security policy to not allow creation of static IAM users. Is there a possibility to add the data source in any other way, like for example using EC2 IAM role?

There is a document describing the manual import of CUR: https://hystax.com/documentation/optscale/e2e_guides/e2e_aws_root_manual_import.html
which is a possible solution, but it also needs a data source to be created with AWS credentials first.

Thanks in advance,
Paweł

**Comment by maxb-hystax** [comment]
Hi Paweł!

Connection with EC2 IAM role is not supported at the moment, only IAM users.

**Comment by pawelh-dbs** [comment]
Thank you

**Comment by lisinan88** [comment]
> Hi Paweł!
> 
> Connection with EC2 IAM role is not supported at the moment, only IAM users.

How can we  develop the function ,change the credential connect type ?
