### ISSUE TITLE
Adding Oracle Cloud Infrastructure as a datasource

### ISSUE THREAD

**Issue by karthicgit** [hystax/optscale#212]
**Is your feature request related to a problem? Please describe.**
please add Oracle cloud as a datasource .

Is there any plan to add this in the roadmap?

**Comment by hx-nick** [comment]
Hi, we have it in the roadmap for the beginning of 2024. Please email info (at) hystax.com if you want us to prioritize this or if you would like to contribute. Here is a guide: https://github.com/hystax/optscale/blob/integration/documentation/new_cloud_integration.md.

**Comment by Alessandroadr** [comment]
Hello, at the present date there are plans for integration with OCI?

**Comment by OmarAboulMakarem** [comment]
any news on oci integration?

**Comment by maxb-hystax** [comment]
Hi @OmarAboulMakarem!

We finally proved the possibility to implement OCI support in OptScale and currently planning its implementation for Q1'2026. 
Stay tuned!

**Comment by OmarAboulMakarem** [comment]
thank you for your swift reply, this is great news, as we are looking into adopting optscale. definitely will be watching the updates for that

**Comment by LaurentDumont** [comment]
Hiya! Any news on this front? I would be curious to see OCI added to the demo site!

**Comment by IvoVampel** [comment]
Hi, any news on OCI support?

Could you update us?

**Comment by dsup-hystax** [comment]
Hi @IvoVampel 
OCI support is currently still in development. We will be happy to share updates with you as soon as there is further progress.

**Comment by LaurentDumont** [comment]
@dsup-hystax 

I believe a comment was removed here so I won't post it back, but is it possible to keep this issue open in the meantime? Just easier to track updates for OCI support. :)
