### ISSUE TITLE
How to change ingress 80/443

### ISSUE THREAD

**Issue by tguisep** [hystax/optscale#214]
Hello,

I'm trying to change the main ingress (cluster listening on 80/443), to listen on others ports (eg 8082 / 4433).
But I'm not able to find how to do.
I tried but patching the daemonset / configuration on the helm ...
Nothing, it stay bind on 80/443.

Any suggestion ?

Thanks,

Thomas.

**Comment by maxb-hystax** [comment]
Hi!
We're looking on it in our lab, will return once we'll write an instruction.

**Comment by sd-hystax** [comment]
Hi, @tguisep !
According [documentation](https://kubernetes.io/docs/concepts/services-networking/ingress/#what-is-ingress:~:text=An%20Ingress%20does%20not%20expose%20arbitrary%20ports%20or%20protocols.%20Exposing%20services%20other%20than%20HTTP%20and%20HTTPS%20to%20the%20internet%20typically%20uses%20a%20service%20of%20type%20Service.Type%3DNodePort%20or%20Service.Type%3DLoadBalancer), an Ingress does not expose arbitrary ports or protocols.
