### ISSUE TITLE
local workflow / k8s deployment changes

### ISSUE THREAD

**Issue by adrien-barret** [hystax/optscale#218]
Hi there,

I tried with ansible, ./runkube ... on a local or AKS envs but the deployments seems not consistent or let's say not working. packages problems, scripts without  output to debug it correctly, etc... Is there any like more complete doc on how the solution work? 

I can try to make a PR to may be have a more vanilla deployment but I need more information on how it work

**Comment by v-hx** [comment]
Hi,

Currently, the only available deployment option involves spinning up a Kubernetes cluster following the installation instructions. Please refer to the README.md file located in the root of the repository.

We have plans to extend support to other platforms and improve the deployment experience, which will require our time for investigation and implementation.

Thank you for reaching out.

**Comment by adrien-barret** [comment]
I understand but tbh the readme doesn't cover azure cloud, and why the need of ip adresse in the install command? it can be managed by helm at some point. 

Is it possible to have like a preview to test your extended support when you'll do it?
