### ISSUE TITLE
Cost and Usage Report is depricating ? what is the plan to handle this transition ?

### ISSUE THREAD

**Issue by deepakpal-in** [hystax/optscale#220]
**Is your feature request related to a problem? Please describe.**
I seen sometime that AWS Cost and Usage report will be depricating and will be replaced by the AWS Data Exports CUR 2.0. 
What is the plan to handle this transition ?

**Describe the solution you'd like**
Is optscale going to work after this transition seamlessly or we need to make some modifications to accomodate this changes ?

**Describe alternatives you've considered**
Is currently Optscale supports AWS Dataexports CUR 2.0 ?

**Comment by maxb-hystax** [comment]
Hi!

Yes, we've started implementation and aim to deliver support AWS CUR 2.0 in April'24. You'll need to update connection settings, while we are going to maintain smooth transition for existing connections.

**Comment by maxb-hystax** [comment]
Closing - CUR 2.0 is support is delivered.
