### ISSUE TITLE
How to start services in local like NGUI with VITE_proxy in .env?

### ISSUE THREAD

**Issue by shadabmalik096rs** [hystax/optscale#226]

**Comment by ek-hystax** [comment]
Hello @shadabmalik096rs 

Here's a small guide to help you get started

1. Navigate to NGUI Directory:
```
cd ngui/ui
```
2. Configure Environment Variables:
Ensure that you set up the necessary environment variables. For local development, it should be sufficient to specify the VITE_PROXY variable. For detailed guidance on configuring the VITE_PROXY variable, please refer to [this link](https://github.com/hystax/optscale/issues/145).

3. Install Dependencies:
Make sure you have pnpm and node installed, we are currently using node@v20.10.0 and pnpm@8.12.1
```
pnpm i --frozen-lockfile
```
4. Start NGUI Project:
```
pnpm start
```

**Comment by shadabmalik096rs** [comment]
Yes ngui for front end But i want make changes in rest_api classes and test them via postman in my local machine?

**Comment by nk-hystax** [comment]
You may build the custom version of the rest_api.
1. add your code to optscale repo
2. run `. build.sh rest_api` from `optscale` folder to build the new `rest_api:local` image on your local machine
3. delete current `restapi` pod via `kubectl delete pod`

The new restapi pod will include your changes.
