### ISSUE TITLE
wanted to add signed certificates for url how to add certificates to nginx ingress controller

### ISSUE THREAD

**Issue by saileshsp** [hystax/optscale#227]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by saileshsp** [comment]
got it updated certificates via helm upgrade command in k8s-configure by creating new tls secret

**Comment by tm-hystax** [comment]
Hi!
Thank you for your request! 
For convenience, we have added a guide to updating ssl certificate - https://github.com/hystax/optscale/blob/integration/documentation/apply_SSL_certificate.md
