### ISSUE TITLE
ELK/grafana password

### ISSUE THREAD

**Issue by tguisep** [hystax/optscale#23]
Hello,

I'm looking for the user/password of the nginx proxy for the elk stack and grafana. (and maybe after the kibana/grafana password)
I couldn't find it (source code, secrets, configmap...).

`
service/elkservice 
service/grafana   
`

Thanks,

Thomas.

**Comment by tguisep** [comment]
I discovered than it's hardcoded in the docker image.
The username is available, but the password are hashed in the `/etc/nginx/.htpasswd  `

**Comment by nexusriot** [comment]
you can change it [here](https://github.com/hystax/optscale/blob/integration/docker_images/grafana_nginx/htpasswd) then rebuild

**Comment by tguisep** [comment]
Hello,

Yes thank, the issue has been fixed with the rework made recently.

Close.
