### ISSUE TITLE
costanalysis in azure portal and cost in tool are not matching , same happening in aws usage and reports cost 

### ISSUE THREAD

**Issue by saileshsp** [hystax/optscale#239]

**Comment by maxb-hystax** [comment]
Can you please provide details?

**Comment by saileshsp** [comment]
what details are needed ? 
actual cost in azure portal is shown for current month as 929USD, where as in tool 1,101.97USD 
In AWS  cost explorer and usage reports showing data as 701USD where as in tool 612 USD

resource service level when checking cost compute costs are higher than what is shown in portal

**Comment by saileshsp** [comment]
also is there a way to update expense import scheme
