### ISSUE TITLE
The solution is currently being loaded. How to check if it is really processing?

### ISSUE THREAD

**Issue by sarathkrishnan-007** [hystax/optscale#25]
The solution is currently being loaded. This has been the status for the past 5 hours, with nothing shown on the UI. How do I check if any kind of processing is happening. The pods show as Evicted, Running, Completed, Pending, ErrImageNeverPull, but is there a way to check the logs/database to see if anything has been dumped/processed?

**Comment by maxb-hystax** [comment]
Hi, you can check Kibana dashboard to see the logs, it can be accessed on port 30081 by default.
But first you should check what's going on with the pods itself, especially in ErrImageNeverPull state.

**Comment by sarathkrishnan-007** [comment]
I've checked, and quite a lot of pods are marked as evicted and ErrImageNeverPull, after I started ingesting a few subscription data. 
I'm unable to connect to the kibana dashboard as I couldn't find creds for the same. I wish the setup documentation could be elaborate for non-dev folks to be able to debug. 
The events log on the UI doesn't show any error message, but the pods have crashed. I don't see any disk space running out either (as there's 1 TB of premium SSD attached) to the VM.

**Comment by nexusriot** [comment]
you can check pod status on the controller node
```
kubectl get pod
```
if you have ErrImageNeverPull please simply pull the image and check storage available disk space 

in other cases check pod wait contitions, for example in 
```
kubectl describe pod restapi-7967ddfd77-ccrr2
```
check for wait-* (just for example)
```
 wait-mariadb:
    Container ID:  docker://f32e1c1ab6ae69bbddd12fe437aea877bc590b16bee4726cbded7831ada01107
    Image:         mariadb:local
    Image ID:      docker://sha256:d2b0622eaedf923a684894d9dc1656f444185da15a24b80df1f3114dd2d56c07
    Port:          <none>
    Host Port:     <none>
    Command:
      sh
      -c
      until mysql --connect-timeout=2 -h mariadb.default.svc.cluster.local -p$MYSQL_ROOT_PASSWORD -e "SELECT 1"; do sleep 2; done
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Tue, 10 Oct 2023 12:04:50 +0400
      Finished:     Tue, 10 Oct 2023 12:04:55 +0400
    Ready:          True
    Restart Count:  0
```
