### ISSUE TITLE
AWS - Pricing force update collection 

### ISSUE THREAD

**Issue by tguisep** [hystax/optscale#27]
Hello,

Aws prices are stored in mongodb/restapi/aws_prices

Is-there a way to force a update of this collection ? (API call...).
I have some issues on it, it would help to diag.

Thanks.

**Comment by maxb-hystax** [comment]
Hi Thomas!

AWS pricings are stored in this collection in a cache-like way. _Insider_ requests pricing from AWS and stores the to this collection it for further use when someone calls /insider/v2/cloud_types/{cloud_type}/flavor_prices.

**Comment by tguisep** [comment]
Yes, I fixed the issue.
Indeed, digging the code, I could reproduce my issue through a call :+1: 

`
curl -X POST "https://xxxxxxxxxx/insider/v2/flavors" -H "accept: application/json" -H "Secret: xxxxxxxxx" -H "Content-Type: application/json" -d "{ \"cloud_type\": \"aws_cnr\", \"cpu\": 2, \"family_specs\": {\"source_flavor_id\": \"t4.small\"}, \"mode\": \"current\", \"os_type\": \"Linux\", \"region\": \"us-east-1\", \"resource_type\": \"instance\"}"
`

**The issue:** 
I had error 500 on that call, because my AWS key/secret was not existing anymore. 
I deleted it to replace by one other and updated the overlay + re-applying ./runkube.py in --uptade-only (...).
But the key and secret has not been updated in the store (etcd), so pods were still using the previous one. (seen by a print(config) in insider-api/contoler/flavor.py)
I couldn't find a way to refresh this data in the etcd, I was thinking that the key would be updated.

**Comment by maxb-hystax** [comment]
Hi, you can change it directly in etcd:
`kubectl exec -ti etcd-0 etcd-walker`
then navigate to /service_credentials/aws/ and change them.

**Comment by tguisep** [comment]
I didn't known this possibility.
Tried just now, that is amazing :100:
