### ISSUE TITLE
Cost optimization for all of the AWS accounts under an organization is not getting generated while connecting via organization root account

### ISSUE THREAD

**Issue by Sri-Prakhya** [hystax/optscale#278]
**Describe the bug**
We have almost 20 AWS accounts and they are under an AWS organization. Billing is configured to be generated in the organization account for all of the other accounts resources as well.
 
As per the documentation, We have created an IAM user in the AWS Organization root account and provided required permissions for CUR and CloudWatch (These permissions are for AWS Organization root account only.) Using this IAM user we have created a data source in the optscale as a Root AWS account link.
 
While checking for the recommendations we are not able to see some good recommendations as well as in the resources section we are not able to see all of the resources from complete organizations as well.
 
I doubt that it is analyzing resources of all of the AWS accounts which are part of the AWS organization and generating recommendations correctly.
 
**To Reproduce**
created an IAM user in the AWS Organization root account
provided required permissions for CUR and CloudWatch (These permissions are for AWS Organization root account only.) 
Using this IAM user create a data source in the optscale as a Root AWS account link. 
Observe the recommendations and resources
 
**Expected behavior**
Analysis of all of the resources from all of the AWS accounts under AWS organization. 
Recommendations generation for cost saving for all of the AWS account part of the organization
 
 
**Additional context**
There is no clear documentation on setting up the connection with the AWS Root account of an AWS organization which is managing multiple AWS accounts and have consolidated billing enables.
Documentation is very much over lapping and not clear enough to implement correctly.
 
**Please provide clear steps to setup this kind of data connection where one AWS organization root account has multiple AWS accounts and consolidated billing is enabled.**

**Comment by Sri-Prakhya** [comment]
@maxb-hystax @v-hx 
Can you please investigate on this issue. This is one of the core issue every organization will face while implementing this tool. Thus seems important to handle.

**Comment by maxb-hystax** [comment]
Hi @Sri-Prakhya!

OptScale supports Linked accounts and consolidated billing - you need to connect root account first (as you correctly did), and then connect Linked accounts as described here - https://hystax.com/documentation/optscale/e2e_guides/e2e_aws.html#connecting-an-aws-linked-account
The Linked account connections will use billing data from the Root one, and their keys to discover resources, getting metrics etc.
Or, you can connect Linked account like a Root one - creating its own CUR and using this guide - https://hystax.com/documentation/optscale/e2e_guides/e2e_aws.html
Hope this helps
