### ISSUE TITLE
Google SSO

### ISSUE THREAD

**Issue by bruumnml** [hystax/optscale#29]
I can't find where to setup the SSO with Google. Is there any updated documentation? Does this function works for free accounts?

**Comment by maxb-hystax** [comment]
Hi! Google SSO is not integrated, OptScale only supports Google OAuth2 flow.

**Comment by bruumnml** [comment]
thanks!
do you have any documentation on how to do it?

**Comment by maxb-hystax** [comment]
You need to create OAuth2 Client in your GCP project - https://console.cloud.google.com/apis/credentials and create OAuth consent screen here - https://console.cloud.google.com/apis/credentials/consent

Then, just put Client ID into overlay parameter _google_oauth_client_id_ in https://github.com/hystax/optscale/blob/integration/optscale-deploy/overlay/user_template.yml and use it for deployment.
If you already deployed OptScale, you can edit it in etcd using `kubectl exec -ti etcd-0 etcd-walker` and then start a new pod of ngui service.
