### ISSUE TITLE
How to run optscale over local machine

### ISSUE THREAD

**Issue by puneet-nayal** [hystax/optscale#291]
**Is your feature request related to a problem? Please describe.**
With the available docs, we are not able to run the application end to end in our local machine which includes UI and backend
**Describe the solution you'd like**
It would be really helpful if we have a proper documentation which would help us in nstalling and using optscale in our local machine, screenshots would be an enhancement with updated docs

**Additional context**
Please also share a community link

**Comment by v-hx** [comment]
@puneet-nayal, could you please specify the exact issues you encountered while trying to set up an Optscale cluster?
Please follow the documentation and let us know if there are any inaccuracies.

https://github.com/hystax/optscale?tab=readme-ov-file#getting-started

**Comment by puneet-nayal** [comment]
@v-hx I have executed till the below command
 ./runkube.py --with-elk  -o overlay/user_template.yml -- <deployment name> <version>
How would I host the UI afterwards.

**Comment by v-hx** [comment]
@puneet-nayal, once you finish the installation, the UI will be available at your machine's IP address/domain. If you have already edited the optscale-deploy/overlay/user_template.yml template according to your needs and have run the Ansible command previously, you are good to go with the command you mentioned.

**Comment by nkc1285** [comment]
Man I've been trying to install this for the last 1 week, but the steps seem to be to complex to understand and eventually after I end-up deploying the cluster, pods are stuck in pending state forever.
