### ISSUE TITLE
how to update/change password from backend

### ISSUE THREAD

**Issue by saileshsp** [hystax/optscale#292]
hi how to update or change password of an user who has forgotten password from backend

**Comment by maxb-hystax** [comment]
Hi @saileshsp 
Please use PATCH /auth/v2/users/{user_id} - https://my.optscale.com/auth/v2/swagger/spec.html#/users/patch_auth_v2_users__user_id_ with cluster secret authorization. Cluster secret can be found in etcd, look for /secret/cluster key.
