### ISSUE TITLE
Is the code in the shape that can be forked and used as is

### ISSUE THREAD

**Issue by mdevengine13** [hystax/optscale#3]
It looks like the code doesn't have the dependencies (versions) correctly setup and hence I couldn't get it to run locally as is. However, running the deployment scripts work since the images are downloaded from the private docker repository of optscale. Is that by design or am I wrong in my assessment?

**Comment by maxb-hystax** [comment]
Yes, we haven't published full build pipelines yet. Working on that, aiming to publish them next month. 
Stay tuned!

**Comment by AlladiPO** [comment]
thanks! but the code in this condition works?

**Comment by asasas234** [comment]
That said, next month, will there be an easier way to deploy optscale locally? Currently looking at the current deployment documentation, I don't understand how it is being installed, will there be a simpler and easier to understand way to install optscale by then?

**Comment by maxb-hystax** [comment]
@asasas234 can you please let us know what inconsistencies do you see in the deployment instructions? We're open to suggestions how to improve the deployment.
At the moment deployment is performed using our own automation, from pre-built images. The plan for the next month is to publish build pipelines to unlock everyone on building the images from the source. Then, we are going to update deployment scheme to be completely based on Helm charts, without custom scripts.

**Comment by lariskovski** [comment]
@maxb-hystax I was also having problems following the deploy documentation. It's confusing using the custom scripts. I'm looking forward for the new deployment scheme with Helm charts 🎉 Thanks for the update.

**Comment by srenzo** [comment]
> That said, next month, will there be an easier way to deploy optscale locally? Currently looking at the current deployment documentation, I don't understand how it is being installed, will there be a simpler and easier to understand way to install optscale by then?

Where did you find the installation documentation @asasas234 ?

**Comment by E1v1s** [comment]
any updates about helm chart? :)

**Comment by SalahBellagnaoui** [comment]
Any news on the new deployment guide with helm charts please ?

**Comment by rogdex24** [comment]
@maxb-hystax Any update on the build pipelines to build images from source ?

**Comment by maxb-hystax** [comment]
Released fully buildable source - https://github.com/hystax/optscale/releases/tag/2023092001-public
