### ISSUE TITLE
Resources not being discovered on Master (DPA) account. Set up using Linked account instructions

### ISSUE THREAD

**Issue by SunnyOd** [hystax/optscale#300]
Hi,

My Optscale install is having problems detecting resources on our DPA/Master account after setting it up using the [Linked Account instructions](https://hystax.com/documentation/optscale/e2e_guides/e2e_aws_linked.html). I'm not sure if these are the right instructions to use for a DPA/Master account?

Our supplier has asked us to use their Master/DPA account to add clients to so they can benefit from the discounts which they offer. We access the Master/DPA account by switching to our DPA role on our Linked account, which then takes us to the DPA Account.

I've followed the Linked account instructions and have created the `optscale` user with our supplier's boundary permissions, and with the permissions that the instructions stated. Then I added CLI/programmatic access to the user (I've also tried 3rd party access keys but this has same issue). Then all I did was create a new "Linked Account" connection in the Optscale UI and added the new Optscale CLI keys there. 

I've managed to get a standard root account setup and it works great using the [AWS Root instructions](https://hystax.com/documentation/optscale/e2e_guides/e2e_aws_root_nocur.html). So I'm happy with the install itself

When I check the events log, there are no warnings or errors. It also shows DPA/Master account being added, along with Rule and Pool but no resources are being detected at all and it's been running for a few days now. There are lots of entries for the _Root_ account which I added previously and it shows resources being detected within minutes of adding the CUR and credentials. 

On the [Optscale Documentation for adding a linked account](https://hystax.com/documentation/optscale/e2e_guides/e2e_aws_linked.html) it does have a note which states:

> "If you only specify a AWS Linked account without providing credentials for the main one, OptScale will not be able to import any billing data."

TBH, I don't fully understand what this means or if it's applicable to my setup as there are no options to add credentials in the Linked account UI other than Keys. In this context, what does the note mean by "main one", would that be the linked account I connect to the DPA account from? Does Optscale support DPA/Master account configurations like I have?

Appreciate any help :)

Thank you,
Sunny

**Comment by stanfra** [comment]
Hi @SunnyOd, you can create CUR report in your Linked account and connect it without Master account

**Comment by SunnyOd** [comment]
> Hi @SunnyOd, you can create CUR report in your Linked account and connect it without Master account

Thanks. I got it working using this approach 👍
