### ISSUE TITLE
Unable to run the ansible command

### ISSUE THREAD

**Issue by laurie-kepford** [hystax/optscale#31]
I have created a single EC2 instance that meets the requirements stated.
I SSHed into the instance and started running the install commands.

This command fails:
ansible-playbook -e "ansible_ssh_user=ubuntu" -k -K -i "10.70.2.60," ansible/k8s-master.yaml

I am using ubuntu which has no password.
I am running this on the instance itself so why does it need to SSH.  
From the documentation, I had assumed all the commands listed were to be directly on the instance, do I have that wrong?
Do I need to create a specific users/pass combination on the target server and then run this command from a separate server?

Please let me know.

**Comment by nexusriot** [comment]
Could you please provide output?

**Comment by laurie-kepford** [comment]
```
ubuntu@ip-10-70-2-60:~/optscale/optscale-deploy$ ansible-playbook -e "ansible_ssh_user=ubuntu" -K -i "10.70.2.60," ansible/k8s-master.yaml
BECOME password:

PLAY [all] *************************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************
fatal: [10.70.2.60]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ubuntu@10.70.2.60: Permission denied (publickey).", "unreachable": true}

PLAY RECAP *************************************************************************************************************
10.70.2.60                 : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0
```
It should be noted that in AWS EC2 ubuntu user does not have a password, so I left that blank.  I am thinking this is the problem.

If I am already SSH'd into the instance, wouldn't there be a different command?

**Comment by laurie-kepford** [comment]
I went back and created a user named optscale, and created an ssh key for it.
Then I ran the entire install as that user.
The installation completed after that.

So if anyone is trying to run this on an EC2 instance you need to create a user.  My example:
```
sudo adduser optscale
pw: yourpassword
sudo usermod -aG sudo optscale
```
Create SSH Key
```
ssh-keygen -t rsa
cat ~/.ssh/id_rsa.pub
nano ~/.ssh/authorized_keys
```
Copy the contents of id_rsa.pub
```
chmod 600 ~/.ssh/authorized_keys
```
Change to that user
```
su optscale
```
Then, the host fingerprint needs to be added to the known hosts file.  Easiest way to do this is to ssh to itself:

```
ssh -i ~/.ssh/id_rsa optscale@IPADDRESS
The authenticity of host 'IPADDRESS (IPADDRESS)' can't be established.
ECDSA key fingerprint is SHA256:9EOmIzF1GisILso03ZVCgw+ggY42FiSFnzy+EFjPrGs.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'IPADDRESS' (ECDSA) to the list of known hosts.
```
Then run the commands as the instructions say.

**Comment by bharath144** [comment]
I went through the same exercise as you did, found that the instructions weren't clear and finally got it working. I should have looked at the Open issues before spending half a day on debugging the issue of why the deployment wasn't going through. Perhaps a PR to update the deployment instructions will help other interested users. I will create one.

**Comment by maxb-hystax** [comment]
Thanks @bharath144 !
