### ISSUE TITLE
Unable to Configure Cost and Usage Report (CUR) 2.0

### ISSUE THREAD

**Issue by josepheichers95** [hystax/optscale#319]
Hi,

You have provided the steps for the cost and usage report and how to set up, create, and connect it. I need to configure or set up CUR 2.0 and access that data. I have taken the steps, but I am facing an error: Unable to configure a billing report: Unable to find report with required configuration.

I have a doubt: can we set up both CUR reports in one bucket, or do we need to create separate configurations? Can you give me the steps to configure the CUR 2.0 and set it up correctly?

**Comment by josepheichers95** [comment]
Hi @maxb-hystax, could you please provide the solution to my issue with configuring CUR 2.0? I'm encountering an error ('Unable to find report with required configuration') and need assistance. Thank you!

**Comment by tm-hystax** [comment]
Hello! 
Depending on what you need, use one of the instructions below.

## Migrate CUR to CUR 2.0 (using an existing bucket)

Use this case if you have already connected an AWS Data Source (on CUR schema) and want to configure CUR 2.0 data into the same bucket.

1\. Create a new Data Export with CUR 2.0 schema. Open the *Data Exports* page in the *AWS Cloud Console*.

Set the *Export type* as "Standard data export" and specify an "Export name". The content of the "Export name" 

field will be required when updating an AWS data source in your OptScale account.

![image](https://github.com/user-attachments/assets/a0595912-ce96-4a21-b4ab-f36a1c16e8aa)

In the *Data table content settings* section select the "CUR 2.0" data table and switch on the “Include resource IDs“

in the *Additional export content*.

![image](https://github.com/user-attachments/assets/b4ace12c-a13d-46fe-a0f7-1aba6f6b839c)

Select an existing bucket in the *Data export storage settings* section.

![image](https://github.com/user-attachments/assets/246a6a50-eab1-41a8-af6f-9c051e56eb0e)

**Input NEW S3 path prefix**

2\. Click on the existing AWS data source on the *Data Source* page. The page with detailed information opens.

Click the *UPDATE CREDENTIALS* button to update the Data Source credentials. Switch on *Update Cost & Usage Report parameters*

to update info about the billing bucket.

![image](https://github.com/user-attachments/assets/589c1875-24a6-4bb0-92a5-509272b03a4f)

Update "Report name" and "Report path prefix", save and wait for a new report to import!

## Migrate CUR to CUR 2.0 (using a new bucket)

Use this option if you have connected an AWS data source and want to edit billing data in the CUR 2.0 schema within a new bucket.

1\. Create a new Data Export with CUR 2.0 schema. Open the *Data Exports* page in the *AWS Cloud Console*.

Set the *Export type* as "Standard data export" and specify an "Export name". The content of the "Export name" 

field will be required when updating an AWS data source in your OptScale account.
![image](https://github.com/user-attachments/assets/aae6f2a1-a630-4f4a-8edd-64bde30a9e85)

In the *Data table content settings* section select the "CUR 2.0" data table and switch on the “Include resource IDs“

in the *Additional export content*.

![image](https://github.com/user-attachments/assets/d05ce791-c963-4536-9619-1678378c510c)

Configure a new bucket in the *Data export storage settings* section. The content of the "S3 path prefix" and "S3 bucket name"

fields will be required when updating an AWS data source in your OptScale account.
![image](https://github.com/user-attachments/assets/fd90662c-67f9-4a2f-9de5-f96665e31e1d)

2\. Click on the existing AWS data source on the *Data Source* page. The page with detailed information opens.

Click the *UPDATE CREDENTIALS* button to update the Data Source credentials. Switch on *Update Cost & Usage Report parameters*

to update info about the billing bucket.
![image](https://github.com/user-attachments/assets/904a8e0f-72bd-44c7-91ca-d0b70e9b34f7)

Enter "Export name" from the first step as "Report name", "S3 bucket name"

as "Report Amazon S3 bucket name", and "S3 bucket name" as "Report path prefix".

Save and wait for a new report to import!

## Setting up export in CUR 2.0 format and connect AWS Data Source to OptScale

1\. Create a new Data Export with CUR 2.0 schema. Open the *Data Exports* page in the *AWS Cloud Console*. 

Set the *Export type* as "Standard data export" and specify an "Export name". The content of the "Export name" 

field will be required when tracking a new AWS data source in your OptScale account.

![image](https://github.com/user-attachments/assets/19ea27f4-792b-4e0a-87a9-2b467a02094c)

In the *Data table content settings* section select the "CUR 2.0" data table and switch on the “Include resource IDs“

in the *Additional export content*.
![image](https://github.com/user-attachments/assets/2f32566d-48b3-4de8-98ac-ac5a95329d1c)

Configure a new bucket in the *Data export storage settings* section. The content of the "S3 path prefix" and 

"S3 bucket name" fields will be required when tracking a new AWS data source in your account.

![image](https://github.com/user-attachments/assets/d78dada4-db42-4d57-9684-3275b0b35a34)

2\. To track a new AWS data source in your OptScale account, please select the **AWS Root Account** tab at the Data Source Connection step during the initial configuration or later on in the Settings section of the main page. Switch off *Automatically detect existing Cost & Usage Report*.

![root_account_cur2](https://github.com/user-attachments/assets/81ae9918-51bf-4bcf-9e7d-a31037249ee6)

Enter "Export name" from the first step as "Report name", "S3 bucket name"  as "Report Amazon S3 bucket name", and "S3 bucket name" as "Report path prefix". 

"Connect" to the Data Source.

**Comment by josepheichers95** [comment]
@tm-hystax -The billing report configuration issue persists despite following the steps correctly. Screenshots provided below for reference and can you provide detailed documentation 
![Screenshot from 2024-07-17 13-38-33](https://github.com/user-attachments/assets/12ef0423-ab79-459f-b329-52dc0e713d8f)
![Screenshot from 2024-07-17 13-38-05](https://github.com/user-attachments/assets/a7ac5f59-a0f0-433c-851c-299322837f31)
![Screenshot from 2024-07-17 13-38-21](https://github.com/user-attachments/assets/88b64487-afc0-4f4e-80e6-5fdcdb258229)
![Screenshot from 2024-07-17 14-27-21](https://github.com/user-attachments/assets/cfc2611b-a47b-4295-ae22-f413787105fc)

**Comment by tm-hystax** [comment]
@josepheichers95, when connecting the data source, you select the checkbox "Automatically detect existing Cost & Usage Report", which currently searches for reports in CUR 1.0.  This needs some reworking on our part.

You need to repeat the following steps:
into OptScale
1) Deselect "Automatically detect existing Cost & Usage Report" 
2) Select "Connect only to data in bucket"
3) Enter your bucket and Data Export information (from your screens):
<img width="1272" alt="help" src="https://github.com/user-attachments/assets/391c16da-500f-4b31-993d-a8114868feac">

**Comment by josepheichers95** [comment]
@tm-hystax - "argument of type 'NoneType' is not iterable" occurs when attempting to iterate over a None value, which is not an iterable. In connecting to data 2.0 as per the provided instructions, the connection is failing, resulting in missing tags and paid networking data, and showing the cost as zero. Ensure all data sources are properly connected and validated to avoid None values during iteration.

**Comment by tm-hystax** [comment]
@josepheichers95, can you confirm if you've connected a cloud account, or is it not possible due to the error "argument of type 'NoneType' is not iterable"?
Please, provide screen from Data Source page and ADVANCED tab for connected data source (if you have it).


If you encounter an error in the same place as shown in the picture, please follow these steps:
<img width="975" alt="Untitled 3" src="https://github.com/user-attachments/assets/91406b86-b74e-447a-9ca0-f55cb400c23e">
1) Open ```http://cluster_ip:30081```
2) Use the username and password from your own ```user_template.yaml``` file (https://github.com/hystax/optscale/blob/integration/optscale-deploy/overlay/user_template.yml#L102)
3) Go to the "Discover" tab
4) Filter the data by container name ```container_name: *diworker*```
5) Add a "message" filter
<img width="1118" alt="Untitled 2" src="https://github.com/user-attachments/assets/9b3f7498-4692-4c1f-b402-71f9dcc53a67">
6) Copy and attach the log with the error

NOTE: if kibana prompts you to create an index pattern, create it with the following parameters:
<img width="1270" alt="Untitled 4" src="https://github.com/user-attachments/assets/174f9ca3-ed8e-4682-8335-6bfcb399567b">

**Comment by josepheichers95** [comment]
@tm-hystax  - Please find below screen-shot 
![Screenshot from 2024-07-19 10-49-55](https://github.com/user-attachments/assets/52a44000-3ebd-45e1-b836-2ed2165efa6d)

**Comment by tm-hystax** [comment]
@josepheichers95, thanks for the provided information.
Could you please provide the diworker logs according to the instructions in the comment above?

**Comment by puneet-nayal** [comment]
@tm-hystax Facing same issue below are the required screenshots
![Screenshot-8](https://github.com/user-attachments/assets/5b86685a-6186-4b6a-8ad6-8c8e023b3105)

**Comment by puneet-nayal** [comment]
@tm-hystax I am also facing same issue, below are the requested screenshots
![image](https://github.com/user-attachments/assets/ced197a9-eef8-4c35-bba5-813b3a40a36c)
![image](https://github.com/user-attachments/assets/269e9e21-f180-46de-8555-7c39ecea51c9)

**Comment by tm-hystax** [comment]
@puneet-nayal , hi!

Based on your screenshot, there is no report file in the bucket you specified on Data Source connection. 

1) Make sure you have a report file in your bucket. Please note that if you created a report today, the report file from the cloud will appear in bucket tomorrow. 
2) Make sure that you have specified the bucket name, prefix and report name correctly.

If you are still encountering the problem, please create a separate issue.
Please attach screenshots of what you have in the bucket(into AWS Cloud Console -> S3), information about the bucket that is indicated in the report (AWS Cloud Console -> Data Exports), and bucket info from OptScale (DETAILS tab of your Data Source) in this case.
