### ISSUE TITLE
Ubuntu Support

### ISSUE THREAD

**Issue by makkipasha** [hystax/optscale#330]
Is Latest version of Ubuntu is support? As on aws ec2 we dnt have Ubuntu 20.04 anymore supported.

**Comment by stanfra** [comment]
Hi @makkipasha, We implement latest version of Ubuntu in upcoming releases, but if you need ti start cluster on Ubuntu 24.04 now please following instruction from READ.me but with some changes:

1) Do not install python 3.9, we will use 3.12  which installed by default, so on “Docker and k8s installation” step from manual perform commands:
` sudo apt update → sudo apt install python3-pip sshpass git python3-virtualenv`
And create virtual env using command: ` virtualenv -p python3 venv`
2) **Before installing requirements need to change ansible version to 9.0.0** in file /optscale-deploy/requirements.txt  and then execute commands: `source venv/bin/activate → pip install -r requirements.tx`

3) Before you start ansible-playbook need to change: 
3.1. docker and k8s versions in file: **optscale-deploy/ansible/roles/common/defaults/main.yaml. Please use  **required_docker_version: "26.0"** and **kubernetes_version: 1.21.14** 
3.2 pip version to **24.0.0** in file **optscale-deploy/ansible/roles/common/tasks/optscale-tools.yaml** in Upgrade pip step
3.3 Need to update rabbitmq template optscale-deploy/optscale/templates/rabbitmq.yaml
Need to change “localhost” to “127.0.0.1” in 2 strings with command:
`wget -O - -q --header "Authorization: Basic `echo -n \"$RABBIT_MANAGEMENT_USER:$RABBIT_MANAGEMENT_PASSWORD\" | base64`" http://localhost:15672/api/healthchecks/node | grep -qF "{\"status\":\"ok\"}"`

After that we need to create config file for docker.  Create folder using command `sudo mkdir -p /etc/systemd/system/docker.service.d/` and config file `sudo touch /etc/systemd/system/docker.service.d/deprecated_manifest.conf.` Open file and add environment variable:
```
[Service]
Environment ="DOCKER_ENABLE_DEPRECATED_PULL_SCHEMA_1_IMAGE=1"
```
After that start ansible playbook and runkube as described in READ.me
