### ISSUE TITLE
Getting below error when we run following command ---virtualenv -p python3.9 venv

### ISSUE THREAD

**Issue by yogi-2023** [hystax/optscale#336]
created virtual environment CPython3.9.5.final.0-64 in 89ms
  creator CPython3Posix(dest=/venv, clear=False, global=False)
  seeder FromAppData(download=False, pip=latest, setuptools=latest, wheel=latest, pkg_resources=latest, via=copy, app_data_dir=/root/.local/share/virtualenv/seed-app-data/v1.0.1.debian.1)
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
root@ip-172-31-34-185:/#

**Comment by stanfra** [comment]
Hi @yogi-2023, this is not error, this is virtual environment creation log. Please continue to follow the instructions to deploy OptScale.
