### ISSUE TITLE
Where is the money ?

### ISSUE THREAD

**Issue by tguisep** [hystax/optscale#34]
Hello,

I'm using the API to process statistics.
But on one of the algorithm, I have a gap (10%) between my results and that I should have.
Through the API, I try to retrieves the cost of each EC2 instance:

Eg:
Cost of march for EC2 from _aws billing us-east-1_ : 20k$
Cost of march for EC2 from the _Optscale UI us-east-1_ : 20k$ (all good)

My algorithm:
```
===> Get all the EC2 for the region:
          cloud_resources = /restapi/v2/organizations/{self.organization_id}/cloud_resources 
          params:  region: us-east-1 
=====> for each **instance** in **cloud_resources**:
         resource_cost = /restapi/v2/resources/{resource_id}/raw_expenses
         params:  start_date=1677628800,  end_date=1680307199  (timestamp retrieved from UX call to be sure to have same timestamps for march)
         total_cost.append(resource_cost['total_cost'])

=== Finally:
sum(total_cost) ==>  18k$
```
So, where are the 2$k differences ?
I discovered than some EC2 are missing in **cloud_resources**.
`/restapi/v2/organizations/{self.organization_id}/cloud_resources`  does-it return the current inventory **only**, or also all the previous resources (it may explain the gap) ? .

Thanks.

**Comment by maxb-hystax** [comment]
Hi!
The API you mention returns only active resources - meaning that these resources has been seen in the cloud recently, so this might be the first reason of the gap. The second possible reason is that /restapi/v2/organizations/{self.organization_id}/cloud_resources requires _type_ parameter, so it returns only resources of that type.

Generally, we have more useful APIs for listing and breaking down resources and their expenses:
/restapi/v2/organizations/{organization_id}/clean_expenses
/restapi/v2/organizations/{organization_id}/summary_expenses
/restapi/v2/organizations/{organization_id}/breakdown_expenses

All of them have the common filtering definition, so requests to them are more or less uniform.
Another useful API for them is /restapi/v2/organizations/{organization_id}/available_filters - to get list of meaningful filter values.

**Comment by tguisep** [comment]
Hey !

As suggested, I used  `/restapi/v2/organizations/{organization_id}/clean_expenses`
And I got all the expense missing.
I had just to manage some meta-data missing ( flavor ), when the instance is not existing anymore.

Thanks !

**Comment by maxb-hystax** [comment]
Nice!
Re meta-data - it is added for the selected types of the resources on their discovery (see discovery-worker), so if you connected cloud account after resource deletion, it won't be enriched with metadata.
