### ISSUE TITLE
can we run nginx ingress of hystax behind another nginx like https://example.org.com/optscale to  redirect url to nginx ingress and access the url 

### ISSUE THREAD

**Issue by saileshsp** [hystax/optscale#342]
can we run nginx ingress of hystax behind another nginx like https://example.org.com/optscale to  redirect url to nginx ingress and access the url

**Comment by stanfra** [comment]
Hi @saileshsp, yes you can. Do you have any problems with this?

**Comment by saileshsp** [comment]
@stanfra  yes facing issues in UI code its not taking base context root

**Comment by stanfra** [comment]
@saileshsp, we checked and this redirect option is not supported
