### ISSUE TITLE
Helm task fails while running the Ansible command

### ISSUE THREAD

**Issue by vg22** [hystax/optscale#35]
I am using Ubuntu 20.04 and k8s version 1.17. Is this version f k8s still supported?
`TASK [k8s-configure : Install nginx ingress controller] ****************************************************************************************************************fatal: [10.0.0.4]: FAILED! => {"changed": true, "cmd": "helm upgrade --install ngingress stable/nginx-ingress --set rbac.create=true --set controller.hostNetwork=true --set controller.extraArgs.default-ssl-certificate=default/defaultcert --set controller.kind=DaemonSet", "delta": "0:10:02.374654", "end": "2023-04-12 18:00:04.699181", "msg": "non-zero return code", "rc": 1, "start": "2023-04-12 17:50:02.324527", "stderr": "E0412 17:50:04.692378  138988 portforward.go:400] an error occurred forwarding 42479 -> 44134: error forwarding port 44134 to pod 58b922e7943c6e9494360d5780fa390aa7ea142a4401c0e7af213f3178ebd009, uid : exit status 1: 2023/04/12 17:50:04 socat[138996] E connect(5, AF=2 10.0.0.4:44134, 16): Connection refused\nE0412 17:50:05.699383  138988 portforward.go:400] an error occurred forwarding 42479 -> 44134: error forwarding port 44134 to pod 58b922e7943c6e9494360d5780fa390aa7ea142a4401c0e7af213f3178ebd009, uid : exit status 1: 2023/04/12 17:50:05 socat[138999] E connect(5, AF=2 10.0.0.4:44134, 16): Connection refused\nE0412 17:50:07.152980  138988 portforward.go:400] an error occurred forwarding 42479 -> 44134: error forwarding port 44134 to pod 58b922e7943c6e9494360d5780fa390aa7ea142a4401c0e7af213f3178ebd009, uid : exit status 1: 2023/04/12 17:50:07 socat[139035] E connect(5, AF=2 10.0.0.4:44134, 16): Connection refused\nE0412 17:50:09.921417  138988 portforward.go:400] an error occurred forwarding 42479 -> 44134: error forwarding port 44134 to pod 58b922e7943c6e9494360d5780fa390aa7ea142a4401c0e7af213f3178ebd009, uid : exit status 1: 2023/04/12 17:50:09 socat[139045] E connect(5, AF=2 10.0.0.4:44134, 16): Connection refused\nE0412 17:50:13.758916  138988 portforward.go:400] an error occurred forwarding 42479 -> 44134: error forwarding port 44134 to pod 58b922e7943c6e9494360d5780fa390aa7ea142a4401c0e7af213f3178ebd009, uid : exit status 1: 2023/04/12 17:50:13 socat[139068] E connect(5, AF=2 10.0.0.4:44134, 16): Connection refused\nE0412 17:50:21.097142  138988 portforward.go:400] an error occurred forwarding 42479 -> 44134: error forwarding port 44134 to pod 58b922e7943c6e9494360d5780fa390aa7ea142a4401c0e7af213f3178ebd009, uid : exit status 1: 2023/04/12 17:50:21 socat[139115] E connect(5, AF=2 10.0.0.4:44134, 16): Connection refused\nE0412 17:50:30.276485  138988 portforward.go:400] an error occurred forwarding 42479 -> 44134: error forwarding port 44134 to pod 58b922e7943c6e9494360d5780fa390aa7ea142a4401c0e7af213f3178ebd009, uid : exit status 1: 2023/04/12 17:50:30 socat[139186] E connect(5, AF=2 10.0.0.4:44134, 16): Connection refused\nE0412 17:50:48.744004  138988 portforward.go:400] an error occurred forwarding 42479 -> 44134: error forwarding port 44134 to pod 58b922e7943c6e9494360d5780fa390aa7ea142a4401c0e7af213f3178ebd009, uid : exit status 1: 2023/04/12 17:50:48 socat[139290] E connect(5, AF=2 10.0.0.4:44134, 16): Connection refused\nE0412 17:51:10.279392  138988 portforward.go:400] an error occurred forwarding 42479 -> 44134: error forwarding port 44134 to pod 58b922e7943c6e9494360d5780fa390aa7ea142a4401c0e7af213f3178ebd009, uid : exit status 1: 2023/04/12 17:51:10 socat[139402] E connect(5, AF=2 10.0.0.4:44134, 16): Connection refused\nE0412 17:51:44.926914  138988 portforward.go:400] an error occurred forwarding 42479 -> 44134: error forwarding port 44134 to pod 58b922e7943c6e9494360d5780fa390aa7ea142a4401c0e7af213f3178ebd009, uid : exit status 1: 2023/04/12 17:51:44 socat[139577] E connect(5, AF=2 10.0.0.4:44134, 16): Connection refused\nE0412 17:52:57.223321  138988 portforward.go:400] an error occurred forwarding 42479 -> 44134: error forwarding port 44134 to pod 58b922e7943c6e9494360d5780fa390aa7ea142a4401c0e7af213f3178ebd009, uid : exit status 1: 2023/04/12 17:52:57 socat[139981] E connect(5, AF=2 10.0.0.4:44134, 16): Connection refused\nE0412 17:54:30.179969  138988 portforward.go:400] an error occurred forwarding 42479 -> 44134: error forwarding port 44134 to pod 58b922e7943c6e9494360d5780fa390aa7ea142a4401c0e7af213f3178ebd009, uid : exit status 1: 2023/04/12 17:54:30 socat[140481] E connect(5, AF=2 10.0.0.4:44134, 16): Connection refused\nWARNING: This chart is deprecated\nE0412 17:55:04.693832  138988 portforward.go:400] an error occurred forwarding 42479 -> 44134: error forwarding port 44134 to pod 58b922e7943c6e9494360d5780fa390aa7ea142a4401c0e7af213f3178ebd009, uid : exit status 1: 2023/04/12 17:55:04 socat[140662] E connect(5, AF=2 10.0.0.4:44134, 16): Connection refused\nE0412 17:55:05.700376  138988 portforward.go:400] an error occurred forwarding 42479 -> 44134: error forwarding port 44134 to pod 58b922e7943c6e9494360d5780fa390aa7ea142a4401c0e7af213f3178ebd009, uid : exit status 1: 2023/04/12 17:55:05 socat[140664] E connect(5, AF=2 10.0.0.4:44134, 16): Connection refused\nE0412 17:55:07.626284  138988 portforward.go:400] an error occurred forwarding 42479 -> 44134: error forwarding port 44134 to pod 58b922e7943c6e9494360d5780fa390aa7ea142a4401c0e7af213f3178ebd009, uid : exit status 1: 2023/04/12 17:55:07 socat[140680] E connect(5, AF=2 10.0.0.4:44134, 16): Connection refused\nE0412 17:55:10.145650  138988 portforward.go:400] an error occurred forwarding 42479 -> 44134: error forwarding port 44134 to pod 58b922e7943c6e9494360d5780fa390aa7ea142a4401c0e7af213f3178ebd009, uid : exit status 1: 2023/04/12 17:55:10 socat[140700] E connect(5, AF=2 10.0.0.4:44134, 16): Connection refused\nE0412 17:55:14.077114  138988 portforward.go:400] an error occurred forwarding 42479 -> 44134: error forwarding port 44134 to pod 58b922e7943c6e9494360d5780fa390aa7ea142a4401c0e7af213f3178ebd009, uid : exit status 1: 2023/04/12 17:55:14 socat[140719] E connect(5, AF=2 10.0.0.4:44134, 16): Connection refused\nE0412 17:55:21.212406  138988 portforward.go:400] an error occurred forwarding 42479 -> 44134: error forwarding port 44134 to pod 58b922e7943c6e9494360d5780fa390aa7ea142a4401c0e7af213f3178ebd009, uid : exit status 1: 2023/04/12 17:55:21 socat[140756] E connect(5, AF=2 10.0.0.4:44134, 16): Connection refused\nE0412 17:55:31.452311  138988 portforward.go:400] an error occurred forwarding 42479 -> 44134: error forwarding port 44134 to pod 58b922e7943c6e9494360d5780fa390aa7ea142a4401c0e7af213f3178ebd009, uid : exit status 1: 2023/04/12 17:55:31 socat[140818] E connect(5, AF=2 10.0.0.4:44134, 16): Connection refused\nE0412 17:55:50.435016  138988 portforward.go:400] an error occurred forwarding 42479 -> 44134: error forwarding port 44134 to pod 58b922e7943c6e9494360d5780fa390aa7ea142a4401c0e7af213f3178ebd009, uid : exit status 1: 2023/04/12 17:55:50 socat[140919] E connect(5, AF=2 10.0.0.4:44134, 16): Connection refused\nE0412 17:56:12.910805  138988 portforward.go:400] an error occurred forwarding 42479 -> 44134: error forwarding port 44134 to pod 58b922e7943c6e9494360d5780fa390aa7ea142a4401c0e7af213f3178ebd009, uid : exit status 1: 2023/04/12 17:56:12 socat[141045] E connect(5, AF=2 10.0.0.4:44134, 16): Connection refused\nE0412 17:56:52.309720  138988 portforward.go:400] an error occurred forwarding 42479 -> 44134: error forwarding port 44134 to pod 58b922e7943c6e9494360d5780fa390aa7ea142a4401c0e7af213f3178ebd009, uid : exit status 1: 2023/04/12 17:56:52 socat[141258] E connect(5, AF=2 10.0.0.4:44134, 16): Connection refused\nE0412 17:58:06.678200  138988 portforward.go:400] an error occurred forwarding 42479 -> 44134: error forwarding port 44134 to pod 58b922e7943c6e9494360d5780fa390aa7ea142a4401c0e7af213f3178ebd009, uid : exit status 1: 2023/04/12 17:58:06 socat[141648] E connect(5, AF=2 10.0.0.4:44134, 16): Connection refused\nE0412 17:59:41.379685  138988 portforward.go:400] an error occurred forwarding 42479 -> 44134: error forwarding port 44134 to pod 58b922e7943c6e9494360d5780fa390aa7ea142a4401c0e7af213f3178ebd009, uid : exit status 1: 2023/04/12 17:59:41 socat[142173] E connect(5, AF=2 10.0.0.4:44134, 16): Connection refused\nError: UPGRADE FAILED: context deadline exceeded", "stderr_lines": ["E0412 17:50:04.692378  138988 portforward.go:400] an error occurred forwarding 42479 -> 44134: error forwarding port 44134 to pod 58b922e7943c6e9494360d5780fa390aa7ea142a4401c0e7af213f3178ebd009, uid : exit status 1: 2023/04/12 17:50:04 socat[138996] E connect(5, AF=2 10.0.0.4:44134, 16): Connection refused", "E0412 17:50:05.699383  138988 portforward.go:400] an error occurred forwarding 42479 -> 44134: error forwarding port 44134 to pod 58b922e7943c6e9494360d5780fa390aa7ea142a4401c0e7af213f3178ebd009, uid : exit status 1: 2023/04/12 17:50:05 socat[138999] E connect(5, AF=2 10.0.0.4:44134, 16): Connection refused", "E0412 17:50:07.152980  138988 portforward.go:400] an error occurred forwarding 42479 -> 44134: error forwarding port 44134 to pod 58b922e7943c6e9494360d5780fa390aa7ea142a4401c0e7af213f3178ebd009, uid : exit status 1: 2023/04/12 17:50:07 socat[139035] E connect(5, AF=2 10.0.0.4:44134, 16): Connection refused", "E0412 17:50:09.921417  138988 portforward.go:400] an error occurred forwarding 42479 -> 44134: error forwarding port 44134 to pod 58b922e7943c6e9494360d5780fa390aa7ea142a4401c0e7af213f3178ebd009, uid : exit status 1: 2023/04/12 17:50:09 socat[139045] E connect(5, AF=2 10.0.0.4:44134, 16): Connection refused", "E0412 17:50:13.758916  138988 portforward.go:400] an error occurred forwarding 42479 -> 44134: error forwarding port 44134 to pod 58b922e7943c6e9494360d5780fa390aa7ea142a4401c0e7af213f3178ebd009, uid : exit status 1: 2023/04/12 17:50:13 socat[139068] E connect(5, AF=2 10.0.0.4:44134, 16): Connection refused", "E0412 17:50:21.097142  138988 portforward.go:400] an error occurred forwarding 42479 -> 44134: error forwarding port 44134 to pod 58b922e7943c6e9494360d5780fa390aa7ea142a4401c0e7af213f3178ebd009, uid : exit status 1: 2023/04/12 17:50:21 socat[139115] E connect(5, AF=2 10.0.0.4:44134, 16): Connection refused", "E0412 17:50:30.276485  138988 portforward.go:400] an error occurred forwarding 42479 -> 44134: error forwarding port 44134 to pod 58b922e7943c6e9494360d5780fa390aa7ea142a4401c0e7af213f3178ebd009, uid : exit status 1: 2023/04/12 17:50:30 socat[139186] E connect(5, AF=2 10.0.0.4:44134, 16): Connection refused", "E0412 17:50:48.744004  138988 portforward.go:400] an error occurred forwarding 42479 -> 44134: error forwarding port 44134 to pod 58b922e7943c6e9494360d5780fa390aa7ea142a4401c0e7af213f3178ebd009, uid : exit status 1: 2023/04/12 17:50:48 socat[139290] E connect(5, AF=2 10.0.0.4:44134, 16): Connection refused", "E0412 17:51:10.279392  138988 portforward.go:400] an error occurred forwarding 42479 -> 44134: error forwarding port 44134 to pod 58b922e7943c6e9494360d5780fa390aa7ea142a4401c0e7af213f3178ebd009, uid : exit status 1: 2023/04/12 17:51:10 socat[139402] E connect(5, AF=2 10.0.0.4:44134, 16): Connection refused", "E0412 17:51:44.926914  138988 portforward.go:400] an error occurred forwarding 42479 -> 44134: error forwarding port 44134 to pod 58b922e7943c6e9494360d5780fa390aa7ea142a4401c0e7af213f3178ebd009, uid : exit status 1: 2023/04/12 17:51:44 socat[139577] E connect(5, AF=2 10.0.0.4:44134, 16): Connection refused", "E0412 17:52:57.223321  138988 portforward.go:400] an error occurred forwarding 42479 -> 44134: error forwarding port 44134 to pod 58b922e7943c6e9494360d5780fa390aa7ea142a4401c0e7af213f3178ebd009, uid : exit status 1: 2023/04/12 17:52:57 socat[139981] E connect(5, AF=2 10.0.0.4:44134, 16): Connection refused", "E0412 17:54:30.179969  138988 portforward.go:400] an error occurred forwarding 42479 -> 44134: error forwarding port 44134 to pod 58b922e7943c6e9494360d5780fa390aa7ea142a4401c0e7af213f3178ebd009, uid : exit status 1: 2023/04/12 17:54:30 socat[140481] E connect(5, AF=2 10.0.0.4:44134, 16): Connection refused", "WARNING: This chart is deprecated", "E0412 17:55:04.693832  138988 portforward.go:400] an error occurred forwarding 42479 -> 44134: error forwarding port 44134 to pod 58b922e7943c6e9494360d5780fa390aa7ea142a4401c0e7af213f3178ebd009, uid : exit status 1: 2023/04/12 17:55:04 socat[140662] E connect(5, AF=2 10.0.0.4:44134, 16): Connection refused", "E0412 17:55:05.700376  138988 portforward.go:400] an error occurred forwarding 42479 -> 44134: error forwarding port 44134 to pod 58b922e7943c6e9494360d5780fa390aa7ea142a4401c0e7af213f3178ebd009, uid : exit status 1: 2023/04/12 17:55:05 socat[140664] E connect(5, AF=2 10.0.0.4:44134, 16): Connection refused", "E0412 17:55:07.626284  138988 portforward.go:400] an error occurred forwarding 42479 -> 44134: error forwarding port 44134 to pod 58b922e7943c6e9494360d5780fa390aa7ea142a4401c0e7af213f3178ebd009, uid : exit status 1: 2023/04/12 17:55:07 socat[140680] E connect(5, AF=2 10.0.0.4:44134, 16): Connection refused", "E0412 17:55:10.145650  138988 portforward.go:400] an error occurred forwarding 42479 -> 44134: error forwarding port 44134 to pod 58b922e7943c6e9494360d5780fa390aa7ea142a4401c0e7af213f3178ebd009, uid : exit status 1: 2023/04/12 17:55:10 socat[140700] E connect(5, AF=2 10.0.0.4:44134, 16): Connection refused", "E0412 17:55:14.077114  138988 portforward.go:400] an error occurred forwarding 42479 -> 44134: error forwarding port 44134 to pod 58b922e7943c6e9494360d5780fa390aa7ea142a4401c0e7af213f3178ebd009, uid : exit status 1: 2023/04/12 17:55:14 socat[140719] E connect(5, AF=2 10.0.0.4:44134, 16): Connection refused", "E0412 17:55:21.212406  138988 portforward.go:400] an error occurred forwarding 42479 -> 44134: error forwarding port 44134 to pod 58b922e7943c6e9494360d5780fa390aa7ea142a4401c0e7af213f3178ebd009, uid : exit status 1: 2023/04/12 17:55:21 socat[140756] E connect(5, AF=2 10.0.0.4:44134, 16): Connection refused", "E0412 17:55:31.452311  138988 portforward.go:400] an error occurred forwarding 42479 -> 44134: error forwarding port 44134 to pod 58b922e7943c6e9494360d5780fa390aa7ea142a4401c0e7af213f3178ebd009, uid : exit status 1: 2023/04/12 17:55:31 socat[140818] E connect(5, AF=2 10.0.0.4:44134, 16): Connection refused", "E0412 17:55:50.435016  138988 portforward.go:400] an error occurred forwarding 42479 -> 44134: error forwarding port 44134 to pod 58b922e7943c6e9494360d5780fa390aa7ea142a4401c0e7af213f3178ebd009, uid : exit status 1: 2023/04/12 17:55:50 socat[140919] E connect(5, AF=2 10.0.0.4:44134, 16): Connection refused", "E0412 17:56:12.910805  138988 portforward.go:400] an error occurred forwarding 42479 -> 44134: error forwarding port 44134 to pod 58b922e7943c6e9494360d5780fa390aa7ea142a4401c0e7af213f3178ebd009, uid : exit status 1: 2023/04/12 17:56:12 socat[141045] E connect(5, AF=2 10.0.0.4:44134, 16): Connection refused", "E0412 17:56:52.309720  138988 portforward.go:400] an error occurred forwarding 42479 -> 44134: error forwarding port 44134 to pod 58b922e7943c6e9494360d5780fa390aa7ea142a4401c0e7af213f3178ebd009, uid : exit status 1: 2023/04/12 17:56:52 socat[141258] E connect(5, AF=2 10.0.0.4:44134, 16): Connection refused", "E0412 17:58:06.678200  138988 portforward.go:400] an error occurred forwarding 42479 -> 44134: error forwarding port 44134 to pod 58b922e7943c6e9494360d5780fa390aa7ea142a4401c0e7af213f3178ebd009, uid : exit status 1: 2023/04/12 17:58:06 socat[141648] E connect(5, AF=2 10.0.0.4:44134, 16): Connection refused", "E0412 17:59:41.379685  138988 portforward.go:400] an error occurred forwarding 42479 -> 44134: error forwarding port 44134 to pod 58b922e7943c6e9494360d5780fa390aa7ea142a4401c0e7af213f3178ebd009, uid : exit status 1: 2023/04/12 17:59:41 socat[142173] E connect(5, AF=2 10.0.0.4:44134, 16): Connection refused", "Error: UPGRADE FAILED: context deadline exceeded"], "stdout": "UPGRADE FAILED\nError: context deadline exceeded", "stdout_lines": ["UPGRADE FAILED", "Error: context deadline exceeded"]}`

**Comment by techbloggy** [comment]
Find any solution of this?

**Comment by nexusriot** [comment]
not absolutely sure, but looks like port forwarding error
```
 42479 -> 44134: error forwarding port 44134 to pod 58b922e7943c6e9494360d5780fa390aa7ea142a4401c0e7af213f3178ebd009, uid : exit status 1: 2023/04/12 17:50:13 socat[139068] E connect(5, AF=2 10.0.0.4:44134, 16): Connection refused
```

**Comment by Scott-Mc** [comment]
I had a similar issue setting this up and had to set the HELM_HOST for it to install the nginx ingress pods.  If it's useful for anyone else looking you can get the IP with

kubectl get svc tiller-deploy -n kube-system

Then

export HELM_HOST="10.x.x.x.x:44134"

Set this to the IP from the first command and run the playbook and it seems to complete.

Didn't have much time to review in detail before moving onto other jobs, but possibly adding this in the playbook,

- name: Retrieve the Cluster IP of tiller-deploy service
  shell: kubectl get svc tiller-deploy -n kube-system -o jsonpath='{.spec.clusterIP}'
  register: tiller_cluster_ip

- name: Set HELM_HOST environment variable
  set_fact:
    helm_host: "{{ tiller_cluster_ip.stdout }}:44134"

and then pass it in the environment for the helm commands is a solution.  

Unclear if that's the best option , if it is I am happy to submit a pull for this.  If there is a better way I am all ears :)

**Comment by stanfra** [comment]
Hi @vg22, our deploy process changed, please try again to spin up the cluster.
