### ISSUE TITLE
Invite user email not being sent

### ISSUE THREAD

**Issue by amandagmsd** [hystax/optscale#357]
**Describe the bug**
I've being trying for days to invite users to my organization but none of the emails I enter are receiving the invite

**To Reproduce**
1. Go to https://my.optscale.com/users/invite
2. Add one or more email 
3. Send invitation
4. No error message
5. No email received (I've check spam)

**Expected behavior**
Receive invitation email

**Additional context**
Using free account

**Comment by stanfra** [comment]
Hello @amandagmsd, please try again, we fixed the problem

**Comment by amandagmsd** [comment]
Hi,
It's working now, thank you
