### ISSUE TITLE
OVH integration 

### ISSUE THREAD

**Issue by tguisep** [hystax/optscale#36]
Hello, 

We are using OVH as secondary cloud provider.
Optscale do not take in charge this Cloud provider.

So:
- Any plan / road map existing about this provider ?

If it's not the case, do you have any advise / starting point  to integrate a new provider ?
It would help to have commit/branch example of a cloud provider integration ? Is-it available somewhere ?

Thanks,

Thomas.

**Comment by maxb-hystax** [comment]
Hi Thomas,

The integration of OVH is not on the roadmap for this and next quarter, at least.
We've checked their billing system some time ago and found it not mature enough for easy integration, so decided to postpone and return to it later.

Just curious - are you looking for integration of their bare metal service of OVH Public Cloud (based on OpenStack)?

And regarding some guidance for the integration of the new cloud - I've published one of the (still internal) documents with checklist of which parts of OptScale should be extended to support a new cloud - https://github.com/hystax/optscale/blob/integration/documentation/new_cloud_integration.md

Best regards,
Max

**Comment by tguisep** [comment]
Indeed, unlike the other providers, OVH propose a bare metal service. Mostly if the cloud part is covered, it would be a first good step. OVH API&Pricing is not so mature than the others cloud providers, but much more simple. 
Thank for the integration document. More than giving the main changes to do, it give good indication about the usage of the differents components (diworker, trapper...).
