### ISSUE TITLE
is there a way to clear all the tables and run the migrations freshly  in mongodb

### ISSUE THREAD

**Issue by saileshsp** [hystax/optscale#361]
i changed the mongod collection path to symlink due to that facing some issues like below
pymongo.errors.DuplicateKeyError: E11000 duplicate key error collection: restapi.raw_expenses index

DB::Exception: Table default.expenses doesn't exist. Stack trace:

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x9451d1a in /usr/bin/clickhouse
1. DB::Exception::Exception<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&) @ 0x9580c83 in /usr/bin/clickhouse
cloud_accounts?details=true api getting failed

wanted to know is there a way to reset db and start freshly or somesolution to fix this issues

**Comment by stanfra** [comment]
Hi @saileshsp, to clear all the tables in db, if you do not have important information on your cluster which you would like to save I recommend you to perform next steps:
1) Delete cluster using runkube.py with -d flag(you can use command which you use to start the cluster and add "-d" after ./runkube.py)
2) Delete /optscale folder
3) Start runkube.py again like you do to start the cluster

All data bases will be cleaned and you will have new cluster
