### ISSUE TITLE
Billing import for GCP fails due to 'NoneType' object has no attribute 'lower'

### ISSUE THREAD

**Issue by Shikhar-Nahar** [hystax/optscale#368]
One of the cloud account source account for GCP the billing import failed with below error.
<img width="770" alt="image" src="https://github.com/user-attachments/assets/c16ab9fb-edfc-41d6-8766-e91c88edd3fc">
Logs from diworker around the time when this failed.
<img width="588" alt="image" src="https://github.com/user-attachments/assets/05309523-30b8-4fc0-bc55-6d49d4df7a11">

@stanfra FYI

_Originally posted by @Shikhar-Nahar in https://github.com/hystax/optscale/issues/366#issuecomment-2277718346_

**Comment by stanfra** [comment]
Hi @Shikhar-Nahar, we have fixed this issue, updated images will be available in tomorrow's release

**Comment by stanfra** [comment]
@Shikhar-Nahar, problem fixed in 2024081401-public
