### ISSUE TITLE
TASK [k8s-configure : Install nginx ingress controller] - connect: no route to host

### ISSUE THREAD

**Issue by joseantoniofernandes** [hystax/optscale#38]
I'm having issues deploying optscale on a VM in Oracle Cloud. Can you help?

`TASK [k8s-configure : Install nginx ingress controller] *******************************************************************************************************************************
fatal: [10.0.0.7]: FAILED! => {"changed": true, "cmd": "helm upgrade --install ngingress stable/nginx-ingress --set rbac.create=true --set controller.hostNetwork=true --set controller.extraArgs.default-ssl-certificate=default/defaultcert --set controller.kind=DaemonSet", "delta": "0:00:02.113905", "end": "2023-04-17 16:09:18.639070", "msg": "non-zero return code", "rc": 1, "start": "2023-04-17 16:09:16.525165", "stderr": "WARNING: This chart is deprecated\nError: UPGRADE FAILED: Get \"https://10.96.0.1:443/api/v1/namespaces/kube-system/configmaps?labelSelector=NAME%!D(MISSING)ngingress%!C(MISSING)OWNER%!D(MISSING)TILLER%!C(MISSING)STATUS%!D(MISSING)DEPLOYED\": dial tcp 10.96.0.1:443: connect: no route to host", "stderr_lines": ["WARNING: This chart is deprecated", "Error: UPGRADE FAILED: Get \"https://10.96.0.1:443/api/v1/namespaces/kube-system/configmaps?labelSelector=NAME%!D(MISSING)ngingress%!C(MISSING)OWNER%!D(MISSING)TILLER%!C(MISSING)STATUS%!D(MISSING)DEPLOYED\": dial tcp 10.96.0.1:443: connect: no route to host"], "stdout": "UPGRADE FAILED\nError: Get \"https://10.96.0.1:443/api/v1/namespaces/kube-system/configmaps?labelSelector=NAME%!D(MISSING)ngingress%!C(MISSING)OWNER%!D(MISSING)TILLER%!C(MISSING)STATUS%!D(MISSING)DEPLOYED\": dial tcp 10.96.0.1:443: connect: no route to host", "stdout_lines": ["UPGRADE FAILED", "Error: Get \"https://10.96.0.1:443/api/v1/namespaces/kube-system/configmaps?labelSelector=NAME%!D(MISSING)ngingress%!C(MISSING)OWNER%!D(MISSING)TILLER%!C(MISSING)STATUS%!D(MISSING)DEPLOYED\": dial tcp 10.96.0.1:443: connect: no route to host"]}

NO MORE HOSTS LEFT ********************************************************************************************************************************************************************

PLAY RECAP ****************************************************************************************************************************************************************************
10.0.0.7                   : ok=68   changed=59   unreachable=0    failed=1    skipped=20   rescued=0    ignored=0`

**Comment by nexusriot** [comment]
did you set correct ip address or it has been changed?
I see different ip addresses 10.0.0.7 and 10.96.0.1
