### ISSUE TITLE
 how Reserved Instance (RI) and Savings Plan (SP) coverage, usage, expenses, and savings are rendered in the UI, including specific calculations for each

### ISSUE THREAD

**Issue by josepheichers95** [hystax/optscale#380]
@nexusriot -explanation on Savings Plan (SP) usage, Reserved Instance (RI) usage, expenses, savings, and total expenses, specifying how each  calculated and represented in the AWS.

**Comment by stanfra** [comment]
Hi @josepheichers95, please take a look in code to find answers to your questions:
backend: https://github.com/hystax/optscale/tree/integration/risp
frontend: https://github.com/hystax/optscale/blob/integration/ngui/ui/src/pages/RiSpCoverage/RiSpCoverage.tsx

**Comment by josepheichers95** [comment]
@stanfra - Can i get some brief explanation RI&SP Rather than code.

**Comment by stanfra** [comment]
@josepheichers95, no docs around this code, please take a look into it.
