### ISSUE TITLE
Deployment on EKS with Updated Helm and Kubernetes Versions

### ISSUE THREAD

**Issue by GiovanniYuriMita** [hystax/optscale#385]
# Is There a Proper Way to Deploy on EKS?
The default OptScale deployment using Ansible works well, but it currently requires an EC2 setup for Kubernetes. It would be greatly beneficial to have the option to deploy on an EKS cluster, given its features and ease of maintenance.

Additionally, the current deployment relies on outdated versions of Helm and Kubernetes, which pose challenges for further customizations within the cluster. I’m interested in knowing if more recent versions of Helm and Kubernetes are compatible with the existing infrastructure.

Is there an official or recommended way to deploy OptScale on an EKS cluster? If so, a guide or documentation on this process would be extremely helpful.

Thank you for your assistance!

**Comment by stanfra** [comment]
Hi @GiovanniYuriMita, we do not have an ability to deploy cluster on EKS now, we are working on supporting new Helm and K8s versions, support will be added in upcoming releases

**Comment by GiovanniYuriMita** [comment]
Hi, @stanfra!

Thank you so much for the quick response.
I am very excited for the future releases that will extend the Kubernetes and helm versions. Thank you for letting me know that it's already planned.

I understand about the EKS compatibility. I will spend some time trying to learn everything about OpSscale to see if I can do something about it.

**Comment by stanfra** [comment]
@GiovanniYuriMita, thank you! If you implement parts of EKS compatibility please create pull request and we take a look on it.

**Comment by GiovanniYuriMita** [comment]
Sure! I will try to understand better the current deployment method and then play around with some other tools to make this functional.

**Comment by Geraldo155** [comment]
Hi, I am currently working on this issue to try and create a way to deploy Optscale on an EKS cluster. Can anyone reopen this issue?

**Comment by VR-Hystax** [comment]
Hello @Geraldo155 
Thank you! If you implement parts of EKS compatibility please create pull request and we take a look on it.
