### ISSUE TITLE
Security: remove default account

### ISSUE THREAD

**Issue by tguisep** [hystax/optscale#40]
Hello,

There is a default account included by default:
`user_root = User('root', type_root, 'root@hystax.com', 'p@ssw0rd',`

I tried & check through the API/UX.
This account is active, for security raison, that should definitively not be the case...

Thomas.

**Comment by maxb-hystax** [comment]
Hi Thomas,

Thank you for finding this. We are making auth db migration to remove it. Please set non-zero value of deleted_at field or delete corresponding record in mariadb - auth-db.user table to workaround this issue for now.

**Comment by tguisep** [comment]
I deleted through the API.
I played directly with the db previously, and I got some unexpected issues, so now I try to avoid it :p
