### ISSUE TITLE
Unable to connect azure databricks in Optscale.

### ISSUE THREAD

**Issue by thameem2195** [hystax/optscale#400]
**Describe the bug**
i have hosted optscale in Ubuntu 24.04, i can connect azure account. i'm trying to connect azure databricks(https://accounts.azuredatabricks.net/) getting invalid request error. but i can connect databricks community(https://accounts.cloud.databricks.com/). both URL are diffeent.

i checked in thet file "databricks.py" located at (tools/cloud_adapter/clouds) . in that file "DATABRICKS_HOST = 'https://accounts.cloud.databricks.com' "  mentioned. 

i have deployed optscale with public image (hystax/arcee:2024090501-public) from docker repo. 

where i need to update the databricks host URL. if i updated i can connect azure databricks?

kindly help me to fix the issue. Thanks.
![Screenshot 2024-09-11 162006](https://github.com/user-attachments/assets/8a34434f-75bc-4644-852b-9154a33ca7f3)

**Comment by nk-hystax** [comment]
Hi @thameem2195! OptScale doesn't support Azure Databricks now, but you may try to update `DATABRICKS_HOST` in `tools/cloud_adapter/clouds/databricks.py` file and build custom images with the updated host value.
From `optscale` folder run the following commands:
```
. build.sh diworker
. build.sh rest_api
```
 to build custom `diworker:local` and `rest_api:local` images and use `kubectl delete pod` to delete running diworker and restapi pods.
