### ISSUE TITLE
Deployment Support on Kubernetes 

### ISSUE THREAD

**Issue by ahmedhkhalil** [hystax/optscale#409]
**Is your feature request related to a problem? Please describe.**
i need to deploy solution on Kubernetes hosted on my environment 

**Describe the solution you'd like**
i need to deploy solution on Kubernetes hosted on my environment 
**Describe alternatives you've considered**

**Additional context**

**Comment by stanfra** [comment]
Hi @ahmedhkhalil, deployment process described in README: https://github.com/hystax/optscale/blob/integration/README.md If you have any problems with Optscale deployment please create issue and describe them. Thank you.

**Comment by ahmedhkhalil** [comment]
hi @stanfra  requested feature is how to deploy application on kuberentes directly , what current exist in provided document is how to deploy application on single virtual machine using ansible and use kuberentes on deployment 
for example we need to have helm charts that used to deploy application on kuberentes or eks
