### ISSUE TITLE
Issues getting pricing for Azure node flavors

### ISSUE THREAD

**Issue by options2015** [hystax/optscale#415]
**Describe the bug**
I am getting this error for all AKS Kubernetes clusters added as a data source.

**To Reproduce**
1. Go to self-hosted web GUI.
2. Add Kubernetes data source.
3. Install helm chart based on instructions given.
4. Wait for the first sync.

**Expected behavior**
The cluster node types price should be discovered.

**Error message**
`Failed to find node Node aks-agentpool-xxxxx-vmssxxxx (provider azure, flavor Standard_B4ms, os type linux, region westeurope) price`
![image](https://github.com/user-attachments/assets/64f39913-0cb3-46b9-b6ad-a69df608d4e5)

I am running version 2024092001-public Latest

**Comment by nk-hystax** [comment]
@options2015 looks like the price for your node configuration is missing in OptScale's db. Could you please check if there are any errors in logs of `insider-worker` service in kibana for the last 24 hours?
