### ISSUE TITLE
Currency

### ISSUE THREAD

**Issue by Upasana1000** [hystax/optscale#42]
If I change the currency, the symbol changes but the value remains remain. Any idea whats happening here?

**Comment by maxb-hystax** [comment]
Hi Upasana,

We didn't implement currency conversion, so organization currency changes two things:
1. Currency symbol shown in UI.
2. Currency checks on cloud account creation - OptScale denies the connection of cloud accounts with a detected currency other than set as organization currency.

Effectively, this means that the user should create a separate organization for each currency they pay in the cloud.
