### ISSUE TITLE
Integrate with Confluent Cloud

### ISSUE THREAD

**Issue by natikoli** [hystax/optscale#422]
I would wish to have an integration with Confluent Cloud for our managed Kafka environments.
Using the `Data Sources` wizard, have the ability to read costs metrics from Confluent.

**Comment by stanfra** [comment]
Hello @natikoli , we don't have plans to implement integration with Confluent cloud in the upcoming releases. If you wish, you can add it yourself (please take a look on https://github.com/hystax/optscale/blob/integration/documentation/new_cloud_integration.md) and post a pull request and our team will review it.
