### ISSUE TITLE
Billing import failed

### ISSUE THREAD

**Issue by gabriel-fas** [hystax/optscale#441]
Billing Import Failed 

See attached diworker elastic log
[Untitled discover search.csv](https://github.com/user-attachments/files/17509952/Untitled.discover.search.csv)

And see web console:

Advanced Messsage

Billing import
Last billing report processed: 
Never
Last billing report attempt: 
7 minutes ago
Status: 
 Failed
Reason: 
argument of type 'NoneType' is not iterable
Monitoring metrics import
Last metrics retrieval: 
8 minutes ago
Last metrics retrieval attempt: 
8 minutes ago
Status: 
 Completed
Discovery
Instance	10/24/2024 06:05 PM	 Completed
Volume	10/24/2024 06:05 PM	 Completed
Snapshot	10/24/2024 06:05 PM	 Completed
Bucket	Never	
 Failed
10/24/2024 06:05 PM
Could not connect to the endpoint URL: "https://cf-templates-ohdkas0d0dip-eu-west-1.s3.EU.amazonaws.com/?publicAccessBlock"
IP Address	10/24/2024 06:05 PM	 Completed

**Comment by tm-hystax** [comment]
@gabriel-fas, hello!
Problem fixed in [2024102901-public](https://github.com/hystax/optscale/releases/tag/2024102901-public)

**Comment by gabriel-fas** [comment]
Resolved
