### ISSUE TITLE
OptScale Underutilized Instances Recommendation Not Generating for Any Data Source

### ISSUE THREAD

**Issue by GiovanniYuriMita** [hystax/optscale#445]
**Describe the bug**
The OptScale Underutilized Instances Recommendation feature does not generate rightsizing recommendations on any data source, including AWS, Azure, and GCP. Over 8 data sources with clear optimization opportunities remain without expected recommendations.

**Steps to Reproduce**

1. Access OptScale Recommendation section.
2. Navigate to Underutilized Instances for any of the connected data sources.
3. Observe missing rightsizing recommendations across AWS, Azure, and GCP environments.

**Expected behavior**
The system should generate rightsizing recommendations for underutilized instances across all data sources with opportunities.

**Screenshots**
![image](https://github.com/user-attachments/assets/b538427c-9372-4bf5-ad70-9801281ab262)

**Additional context**
Other recommendation features operate as expected, including:

- Instances for Shutdown
- Obsolete IPs
- Instances with insecure Security Group settings

Other functionalities, such as resource mapping and billing integrations, are also functioning correctly.

**Comment by stanfra** [comment]
Hi @GiovanniYuriMita , please check that you set service credentials for clouds during cluster initialization in your overlay(https://github.com/hystax/optscale/blob/integration/optscale-deploy/overlay/user_template.yml#L8), OptScale uses them during this recommendation check. Also please check that performance metrics for instances are processed -  you can check them on instance details page (only for active instances) or on data source details: check in the Advanced tab and that the active resource meets the requirements you set to be included in the recommendation. If after all this the resource still does not appear in the recommendation, then please write the region and flavor of this resource so that we can take a look.

**Comment by GiovanniYuriMita** [comment]
Hi @stanfra,

I’ve reviewed the Advanced tab under Data Sources, and everything is configured as expected.
![image](https://github.com/user-attachments/assets/34d42080-e891-4242-8e4f-ff8e4e2d7496)

However, I noticed that I haven’t specified any service accounts for the cloud credentials. Could you clarify the functionality here? Specifically, I’m interested in how the service accounts work across different data sources within my OptScale organizations. As per my understanding, it appears we’re limited to defining only one service account per cloud in the [user_template.yml](https://github.com/hystax/optscale/blob/integration/optscale-deploy/overlay/user_template.yml#L8) file.

Is there a method for setting distinct service accounts per data source, or should I be configuring this differently?

Thank you!

**Comment by stanfra** [comment]
Service credentials used for getting prices from clouds, there are no ability to distinct service accounts per data source, service credentials used for all OptScale cluster.

**Comment by GiovanniYuriMita** [comment]
So it doesn't matter which organization service account is it? It's just for getting the correct prices?

Is it a cluster secret? Is there a way to create/update it without having to run this:

./runkube.py --with-elk  --update-only -- <deployment name>  <version>

**Comment by GiovanniYuriMita** [comment]
Nevermind. I figured it out and adjusted as intended.

Now I am getting rightsizing recommendations for Azure and AWS, but I'll need to make some adjustments to tools\cloud_adapter\clouds\gcp.py in order to make GCP Rightsizing work. 

I'll update this as soon as possible.

**Comment by GiovanniYuriMita** [comment]
@stanfra, I made modifications to dynamically locate the correct pricing table and column names, which were previously hardcoded as hystaxcom.pricing_dataset.cloud_pricing_export and list_price. The hardcoded values caused errors as they didn’t match the table and column names in my project.

Follow the adjustments:

```python
  def _get_pricing_table_schema(self):
        """
        Retrieves the schema of the cloud_pricing_export table.
        """
        try:
            table = self.bigquery_client.get_table(self._pricing_table_full_name())
            schema = table.schema
            LOG.info(f"Retrieved schema for table {self._pricing_table_full_name()}: {[field.name for field in schema]}")
            return schema
        except Exception as ex:
            LOG.error(f"Error retrieving schema for table {self._pricing_table_full_name()}: {ex}")
            raise

    def _identify_pricing_column(self):
        """
        Identifies the pricing column dynamically based on the table schema.
        Returns the column name if found, else raises an exception.
        """
        schema = self._get_pricing_table_schema()
        possible_price_columns = ['list_price', 'unit_price', 'price', 'cost', 'billing_price']  # Extend as needed

        # Search for columns that match possible pricing column names
        for field in schema:
            if field.name.lower() in possible_price_columns:
                LOG.info(f"Identified pricing column: {field.name}")
                return field.name

        # If no exact match, search for columns containing 'price' or 'cost'
        for field in schema:
            if 'price' in field.name.lower() or 'cost' in field.name.lower():
                LOG.info(f"Identified pricing column based on substring match: {field.name}")
                return field.name

        # If no pricing column is found, raise an exception
        raise ValueError(f"No pricing column found in table {self._pricing_table_full_name()}. Please ensure that the table contains a pricing-related column.")
    
    @cached_property
    def pricing_column(self):
        """
        Caches the identified pricing column name.
        """
        return self._identify_pricing_column()

    def _build_pricing_query(self, sku_desription_pattern: str) -> str:
        # sample query that we are building here:
        # SELECT prices.list_price
        # FROM `hystaxcom.pricing_dataset.cloud_pricing_export` prices
        # INNER JOIN (SELECT sku.id as sku_id, max(export_time) as export_time
        #             FROM `hystaxcom.pricing_dataset.cloud_pricing_export`
        #             WHERE service.id = '6F81-5844-456A'
        #               AND sku.description LIKE '%Instance Core running in Delhi'
        #             GROUP BY sku.id) inr
        # ON    prices.sku.id = inr.sku_id
        #   AND prices.export_time = inr.export_time
        inner_query = f"""
        SELECT sku.id as sku_id, max(export_time) as export_time
        FROM `{self._pricing_table_full_name()}`
        WHERE service.id = '{COMPUTE_SERVICE_ID}'
            AND sku.description LIKE '{sku_desription_pattern}'
        GROUP BY sku.id"""
        query = f"""
        SELECT prices.{self.pricing_column}, prices.sku
        FROM `{self._pricing_table_full_name()}` prices
        INNER JOIN ({inner_query}) inr
        ON    prices.sku.id = inr.sku_id
          AND prices.export_time = inr.export_time
        """
        return query
```

After adjusting the code, I got the following warnings indicating that specific instance types couldn’t be priced:

```
INFO:insider.insider_api.handlers.v2.flavors:Received flavor search parameters: {'cloud_type': 'gcp_cnr', 'resource_type': 'instance', 'region': 'southamerica-east1', 'family_specs': {'source_flavor_id': 'e2-medium'}, 'mode': 'current', 'currency': 'BRL'}
INFO:tools.cloud_adapter.clouds.gcp:Identified pricing column: cost
WARNING:tools.cloud_adapter.clouds.gcp:failed to dicover price for c2-standard-16 in southamerica-east1
WARNING:tools.cloud_adapter.clouds.gcp:failed to dicover price for c2-standard-30 in southamerica-east1
WARNING:tools.cloud_adapter.clouds.gcp:failed to dicover price for c2-standard-4 in southamerica-east1
WARNING:tools.cloud_adapter.clouds.gcp:failed to dicover price for c2-standard-60 in southamerica-east1
...
```

After investigating, I updated the _resource_priced_machine_series_descriptions and _special_machine_series_descriptions dictionaries to ensure all necessary GCP instance types were mapped. Here’s the updated structure:

```python
    @cached_property
    def _resource_priced_machine_series_descriptions(self) -> dict:
        return {
            "A2 Instance": "a2",
            "A3 Instance": "a3",
            "C2D AMD Instance": "c2d",
            "Compute optimized": "c2",
            "C3 Instance": "c3",
            "C4 Instance": "c4",
            "E2 Instance": "e2",
            "G2 Instance": "g2",
            "M1 Memory-optimized Instance": "m1",
            "M2 Memory-optimized Instance": "m2",
            "M3 Memory-optimized Instance": "m3",
            "N1 Predefined Instance": "n1",
            "N2 Instance": "n2",
            "N2D AMD Instance": "n2d",
            "N4 Instance": "n4",
            "T2D AMD Instance": "t2d",
            "T2A Arm Instance": "t2a",
            "X4 Instance": "x4",
            "Z3 Instance": "z3",
        }

    @cached_property
    def _special_machine_series_descriptions(self) -> dict:
        return {
            "f1-micro": "Micro Instance with burstable CPU",
            "g1-small": "Small Instance with 1 VCPU",
            "c2-standard": "Standard Compute C2",
            "c2-highcpu": "High CPU Compute C2",
            "c2-highmem": "High Memory Compute C2",
            "c3-standard": "Standard Compute C3",
            "c3-highcpu": "High CPU Compute C3",
            "c3-highmem": "High Memory Compute C3",
            "c4-standard": "Standard Compute C4",
            "c4-highcpu": "High CPU Compute C4",
            "c4-highmem": "High Memory Compute C4",
            "e2-medium": "E2 Medium Instance",
            "e2-small": "E2 Small Instance",
            "e2-micro": "E2 Micro Instance",
            "e2-highcpu": "E2 High CPU Instance",
            "e2-highmem": "E2 High Memory Instance",
            "n1-standard": "Standard Compute N1",
            "n1-highcpu": "High CPU Compute N1",
            "n1-highmem": "High Memory Compute N1",
            "n2-standard": "Standard Compute N2",
            "n2-highcpu": "High CPU Compute N2",
            "n2-highmem": "High Memory Compute N2",
            "n2d-standard": "Standard Compute N2D",
            "n2d-highcpu": "High CPU Compute N2D",
            "n2d-highmem": "High Memory Compute N2D",
            "n4-standard": "Standard Compute N4",
            "n4-highcpu": "High CPU Compute N4",
            "n4-highmem": "High Memory Compute N4",
            "c3d-standard": "Standard Compute C3D",
            "c3d-highcpu": "High CPU Compute C3D",
            "c4d-standard": "Standard Compute C4D",
            "c4d-highcpu": "High CPU Compute C4D",
            "m1-megamem": "Mega Memory M1",
            "m1-ultramem": "Ultra Memory M1",
            "m2-hypermem": "Hyper Memory M2",
            "m2-megamem": "Mega Memory M2",
            "m2-ultramem": "Ultra Memory M2",
            "m3-megamem": "Mega Memory M3",
            "m3-ultramem": "Ultra Memory M3",
            "x4-megamem": "Mega Memory X4",
            "z3-highmem": "High Memory Z3",
            "a2-ultragpu": "Ultra GPU A2",
        }
```

Despite the configuration updates, recommendations for GCP accounts still aren’t populating. Screenshot attached for reference:

```
INFO:tornado.access:200 POST /insider/v2/flavors (10.254.0.26) 17.77ms
INFO:insider.insider_api.handlers.v2.flavors:Received flavor search parameters: {'cloud_type': 'gcp_cnr', 'resource_type': 'instance', 'region': 'southamerica-east1', 'family_specs': {'source_flavor_id': 'n2-highmem-2'}, 'mode': 'current', 'currency': 'BRL'}
INFO:tornado.access:200 POST /insider/v2/flavors (10.254.0.26) 18.84ms
INFO:insider.insider_api.handlers.v2.flavors:Received flavor search parameters: {'cloud_type': 'gcp_cnr', 'resource_type': 'instance', 'region': 'southamerica-east1', 'family_specs': {'source_flavor_id': 'n2-standard-8'}, 'mode': 'current', 'currency': 'BRL'}
INFO:tornado.access:200 POST /insider/v2/flavors (10.254.0.26) 23.44ms
INFO:insider.insider_api.handlers.v2.flavors:Received flavor search parameters: {'cloud_type': 'gcp_cnr', 'resource_type': 'instance', 'region': 'southamerica-east1', 'family_specs': {'source_flavor_id': 'n2-highmem-2'}, 'mode': 'current', 'currency': 'BRL'}
INFO:tornado.access:200 POST /insider/v2/flavors (10.254.0.26) 19.31ms
```

But still I got no recommendations for GCP Accounts
![image](https://github.com/user-attachments/assets/49f36c9d-e359-441f-8a23-2e954e10e139)

**Comment by stanfra** [comment]
Hi @GiovanniYuriMita, please create a pull request or branch with your changes so we can patch our environment on them and identify the problem for GCP cloud.

**Comment by GiovanniYuriMita** [comment]
Hi @stanfra,

I've created the PR: https://github.com/hystax/optscale/pull/448

**Comment by GiovanniYuriMita** [comment]
Hi @stanfra,

After talking to @sd-hystax on the PR, we managed to make it work after adjusting the hardcoded `hystaxcom:pricing_dataset.cloud_pricing_export` to `{self._pricing_table_full_name()}`, enabling the pricing export and adjusting it on the overlay.

Thank you so much for all the help!!

You guys are awesome!

**Comment by nadeem-nasir** [comment]
@GiovanniYuriMita @stanfra 
Hi, I'm experiencing the same issue — Underutilized Instances Recommendation is not generating for my Azure subscription.

I haven't configured service credentials in overlay/user_template.yml. 👉 What permissions are required for these credentials to work correctly?

My Azure subscriptions span multiple regions. 👉 Will OptScale fetch data from all regions, or is it limited to one region only?
