### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable`

### ISSUE THREAD

**Issue by andersanto** [hystax/optscale#45]
I've followed the deployment guide but, I'm stucked on the dployment step. Does someone know why this occurs and/or simply
![error](https://github.com/hystax/optscale/assets/64675033/ce6dcee8-78db-41d5-98a8-942d48988a4f)
 how to solve this?

**Comment by maxb-hystax** [comment]
Hi @andersanto!

Please locate .kube/config file which was created during k8s deployment and try to pass its path as a parameter for runkube.py. See https://github.com/hystax/optscale/blob/integration/optscale-deploy/runkube.py#L333 for the details.
