### ISSUE TITLE
Docker images issue after ./runkube.py --with-elk  command.

### ISSUE THREAD

**Issue by surendra-tanwar** [hystax/optscale#463]
Hello Team , 
As per your documentaion i completed the Kubernetes installation and edit the secret in the usertemplate yaml file. but when in run ./runkube.py --with-elk  -o overlay/user_template.yml -- <deployment name> <version>
my version is 2024110701-public as mention in docker hub.
so when i run this command, pull images from index.docker.io/hystax . how to solve this error give me some idea.
ERROR IS
  File "/home/ubuntu/optscale/optscale-deploy/venv/lib/python3.9/site-packages/docker/api/client.py", line 223, in _raise_for_status
    response.raise_for_status()
  File "/home/ubuntu/optscale/optscale-deploy/venv/lib/python3.9/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://172.35.15.231:2376/v1.35/images/index.docker.io/hystax/metroculus_api:2024110701-public/json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/optscale/optscale-deploy/./runkube.py", line 457, in <module>
    acr.start(args.check, args.update_only)
  File "/home/ubuntu/optscale/optscale-deploy/./runkube.py", line 330, in start
    images = self.pull_images(docker_cl)
  File "/home/ubuntu/optscale/optscale-deploy/./runkube.py", line 147, in pull_images
    image = self._pull_image(docker_cl, image_name, self.version,
  File "/home/ubuntu/optscale/optscale-deploy/./runkube.py", line 133, in _pull_image
    image = docker_cl.images.pull(**params)
  File "/home/ubuntu/optscale/optscale-deploy/venv/lib/python3.9/site-packages/docker/models/images.py", line 311, in pull
    return self.get('{0}:{1}'.format(repository, tag))
  File "/home/ubuntu/optscale/optscale-deploy/venv/lib/python3.9/site-packages/docker/models/images.py", line 212, in get
    return self.prepare_model(self.client.api.inspect_image(name))
  File "/home/ubuntu/optscale/optscale-deploy/venv/lib/python3.9/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/home/ubuntu/optscale/optscale-deploy/venv/lib/python3.9/site-packages/docker/api/image.py", line 240, in inspect_image
    return self._result(
  File "/home/ubuntu/optscale/optscale-deploy/venv/lib/python3.9/site-packages/docker/api/client.py", line 229, in _result
    self._raise_for_status(response)
  File "/home/ubuntu/optscale/optscale-deploy/venv/lib/python3.9/site-packages/docker/api/client.py", line 225, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/home/ubuntu/optscale/optscale-deploy/venv/lib/python3.9/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.ImageNotFound: 404 Client Error: Not Found ("no such image: index.docker.io/hystax/metroculus_api:2024110701-public: No such image: hystax/metroculus_api:2024110701-public")

**Comment by stanfra** [comment]
Hi @suren11111, we started cluster from  2024110701-public today and all images pulled successfully, we checked that metroculus_api:2024110701-public exists in the docker hub. Please try again or try to use latest release 2024111501-public. If the problem occurs again, then attach the entire log starting from the runkube command.

**Comment by surendra-tanwar** [comment]
Here is  My Machine Details  
- **RAM**: 16GB  
- **Storage**: 150GB SSD  
- **OS**: Ubuntu 20.04  

### Steps I perform to Install Optscale  

1. **Install Required Packages**  
   I first updated the system and installed the required packages:  
   sudo apt update  
   sudo apt install python3-pip sshpass git python3-virtualenv python3.9  

2. **Clone the Repository**  
   Next, I cloned the Optscale repository:  
   git clone https://github.com/hystax/optscale.git  
   
3.  cd optscale/optscale-deploy  
  
4.   I prepared a Python virtual environment by running these commands:   
   virtualenv -p python3.9 venv  
   source venv/bin/activate  
   pip install -r requirements.txt  

5.  I used an Ansible playbook to install Kubernetes.
 
   ansible-playbook -e "ansible_ssh_user=myuser" -k -K -i "111.11.11.11," ansible/k8s-master.yaml  
   This command created Kubernetes nodes and started the pods in the `kube-system` namespace. I confirmed that the Tiller pod was running fine on the nodes.  

6. **Deploy Optscale**  
   Finally, I ran the following command to deploy Optscale:  
   ./runkube.py --with-elk -o overlay/user_template.yml -- optscale-deployment-name 2024110701-public  
Now Error is

ERROR IS
File "/home/ubuntu/optscale/optscale-deploy/venv/lib/python3.9/site-packages/docker/api/client.py", line 223, in _raise_for_status
response.raise_for_status()
File "/home/ubuntu/optscale/optscale-deploy/venv/lib/python3.9/site-packages/requests/models.py", line 1024, in raise_for_status
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://172.35.15.231:2376/v1.35/images/index.docker.io/hystax/archee:2024110701-public/json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/ubuntu/optscale/optscale-deploy/./runkube.py", line 457, in
acr.start(args.check, args.update_only)
File "/home/ubuntu/optscale/optscale-deploy/./runkube.py", line 330, in start
images = self.pull_images(docker_cl)
File "/home/ubuntu/optscale/optscale-deploy/./runkube.py", line 147, in pull_images
image = self._pull_image(docker_cl, image_name, self.version,
File "/home/ubuntu/optscale/optscale-deploy/./runkube.py", line 133, in _pull_image
image = docker_cl.images.pull(**params)
File "/home/ubuntu/optscale/optscale-deploy/venv/lib/python3.9/site-packages/docker/models/images.py", line 311, in pull
return self.get('{0}:{1}'.format(repository, tag))
File "/home/ubuntu/optscale/optscale-deploy/venv/lib/python3.9/site-packages/docker/models/images.py", line 212, in get
return self.prepare_model(self.client.api.inspect_image(name))
File "/home/ubuntu/optscale/optscale-deploy/venv/lib/python3.9/site-packages/docker/utils/decorators.py", line 19, in wrapped
return f(self, resource_id, *args, **kwargs)
File "/home/ubuntu/optscale/optscale-deploy/venv/lib/python3.9/site-packages/docker/api/image.py", line 240, in inspect_image
return self._result(
File "/home/ubuntu/optscale/optscale-deploy/venv/lib/python3.9/site-packages/docker/api/client.py", line 229, in _result
self._raise_for_status(response)
File "/home/ubuntu/optscale/optscale-deploy/venv/lib/python3.9/site-packages/docker/api/client.py", line 225, in _raise_for_status
raise create_api_error_from_http_exception(e)
File "/home/ubuntu/optscale/optscale-deploy/venv/lib/python3.9/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
raise cls(e, response=response, explanation=explanation)
docker.errors.ImageNotFound: 404 Client Error: Not Found ("no such image: index.docker.io/hystax/metroculus_api:2024110701-public: No such image: hystax/archee:2024110701-public")

**Comment by stanfra** [comment]
Hi @suren11111 , please check that you do not change file https://github.com/hystax/optscale/blob/integration/optscale-deploy/components.yaml . Because OptScale do not have component named "archee" but as I see in your attached logs that you try to find it. Also if you faced with 404 error again please try to pull image manually using command: `docker pull hystax/metroculus_api:2024110701-public`

**Comment by surendra-tanwar** [comment]
Hi @stanfra  Are the steps I performed from 1 to 7 correct for running the obstacle, or is there any issue in my steps or commands? 
I Try again with latest release 2024111501-public
./runkube.py --with-elk  -o overlay/user_template.yml -- optscale-deployment 2024111501-public
05:32:43.391: Pulling images for 172.31.8.117
05:32:43.395: Pulling image index.docker.io/hystax/arcee with tag 2024111501-public
05:32:51.640: Pulling image index.docker.io/hystax/auth with tag 2024111501-public
05:33:02.091: Pulling image index.docker.io/hystax/bi_exporter with tag 2024111501-public
05:33:09.531: Pulling image index.docker.io/hystax/bi_scheduler with tag 2024111501-public
05:33:15.543: Pulling image index.docker.io/hystax/booking_observer with tag 2024111501-public
05:33:22.577: Pulling image index.docker.io/hystax/bulldozer_api with tag 2024111501-public
05:33:30.016: Pulling image index.docker.io/hystax/bulldozer_worker with tag 2024111501-public
05:33:45.731: Pulling image index.docker.io/hystax/bumischeduler with tag 2024111501-public
05:33:50.560: Pulling image index.docker.io/hystax/bumiworker with tag 2024111501-public
05:34:00.614: Pulling image index.docker.io/hystax/calendar_observer with tag 2024111501-public
05:34:03.990: Pulling image index.docker.io/hystax/cleanelkdb with tag 2024111501-public
05:34:08.917: Pulling image index.docker.io/hystax/cleaninfluxdb with tag 2024111501-public
05:34:14.402: Pulling image index.docker.io/hystax/cleanmongodb with tag 2024111501-public
05:34:22.318: Pulling image index.docker.io/hystax/configurator with tag 2024111501-public
05:34:29.040: Pulling image index.docker.io/hystax/demo_org_cleanup with tag 2024111501-public
05:34:34.953: Pulling image index.docker.io/hystax/diproxy with tag 2024111501-public
05:34:40.663: Pulling image index.docker.io/hystax/diworker with tag 2024111501-public
05:34:56.401: Pulling image index.docker.io/hystax/elk with tag 2024111501-public
05:35:27.931: Pulling image index.docker.io/hystax/error_pages with tag 2024111501-public
05:35:32.305: Pulling image index.docker.io/hystax/etcd with tag 2024111501-public
05:35:41.986: Pulling image index.docker.io/hystax/failed_imports_dataset_generator with tag 2024111501-public
05:35:49.307: Pulling image index.docker.io/hystax/grafana with tag 2024111501-public
05:35:57.499: Pulling image index.docker.io/hystax/grafana_nginx with tag 2024111501-public
05:36:02.406: Pulling image index.docker.io/hystax/herald with tag 2024111501-public
05:36:13.291: Pulling image index.docker.io/hystax/herald_executor with tag 2024111501-public
05:36:19.751: Pulling image index.docker.io/hystax/influxdb with tag 2024111501-public
05:36:26.374: Pulling image index.docker.io/hystax/insider_api with tag 2024111501-public
05:36:39.662: Pulling image index.docker.io/hystax/insider_scheduler with tag 2024111501-public
05:36:44.837: Pulling image index.docker.io/hystax/insider_worker with tag 2024111501-public
05:36:50.434: Pulling image index.docker.io/hystax/jira_bus with tag 2024111501-public
05:37:00.907: Pulling image index.docker.io/hystax/jira_ui with tag 2024111501-public
05:37:08.196: Pulling image index.docker.io/hystax/katara_service with tag 2024111501-public
05:37:16.859: Pulling image index.docker.io/hystax/katara_worker with tag 2024111501-public
05:37:24.933: Pulling image index.docker.io/hystax/keeper with tag 2024111501-public
05:37:32.151: Pulling image index.docker.io/hystax/keeper_executor with tag 2024111501-public
05:37:38.744: Pulling image index.docker.io/hystax/live_demo_generator with tag 2024111501-public
05:37:43.812: Pulling image index.docker.io/hystax/mariadb with tag 2024111501-public
05:37:50.277: Pulling image index.docker.io/hystax/metroculus_api with tag 2024111501-public
05:38:02.034: Pulling image index.docker.io/hystax/metroculus_scheduler with tag 2024111501-public
05:38:07.478: Pulling image index.docker.io/hystax/metroculus_worker with tag 2024111501-public
05:38:16.085: Pulling image index.docker.io/hystax/mongo with tag 2024111501-public
05:38:26.925: Pulling image index.docker.io/hystax/ngui with tag 2024111501-public
05:38:33.504: Pulling image index.docker.io/hystax/ohsu with tag 2024111501-public
05:38:56.493: Pulling image index.docker.io/hystax/organization_violations with tag 2024111501-public
05:39:01.491: Pulling image index.docker.io/hystax/pharos_receiver with tag 2024111501-public
05:39:07.640: Pulling image index.docker.io/hystax/pharos_worker with tag 2024111501-public
05:39:12.077: Pulling image index.docker.io/hystax/redis with tag 2024111501-public
05:39:16.718: Pulling image index.docker.io/hystax/resource_discovery with tag 2024111501-public
05:39:27.398: Pulling image index.docker.io/hystax/resource_observer with tag 2024111501-public
05:39:32.886: Pulling image index.docker.io/hystax/resource_violations with tag 2024111501-public
05:39:38.483: Pulling image index.docker.io/hystax/rest_api with tag 2024111501-public
05:39:56.946: Pulling image index.docker.io/hystax/risp_scheduler with tag 2024111501-public
05:40:02.573: Pulling image index.docker.io/hystax/risp_worker with tag 2024111501-public
05:40:12.740: Pulling image index.docker.io/hystax/slacker with tag 2024111501-public
05:40:23.279: Pulling image index.docker.io/hystax/slacker_executor with tag 2024111501-public
05:40:29.842: Pulling image index.docker.io/hystax/trapper_scheduler with tag 2024111501-public
05:40:35.008: Pulling image index.docker.io/hystax/trapper_worker with tag 2024111501-public
05:40:45.685: Pulling image index.docker.io/hystax/users_dataset_generator with tag 2024111501-public
05:40:52.020: Pulling image index.docker.io/hystax/webhook_executor with tag 2024111501-public
05:40:56.122: Pulling image index.docker.io/hystax/gemini_scheduler with tag 2024111501-public
05:41:00.841: Pulling image index.docker.io/hystax/gemini_worker with tag 2024111501-public
05:41:07.179: Pulling image index.docker.io/hystax/power_schedule with tag 2024111501-public
05:41:20.312: Pulling image index.docker.io/hystax/layout_cleaner with tag 2024111501-public
05:41:24.812: images for tag: {'arcee': <Image: 'hystax/arcee:2024111501-public'>, 'auth': <Image: 'hystax/auth:2024111501-public'>, 'bi_exporter': <Image: 'hystax/bi_exporter:2024111501-public'>, 'bi_scheduler': <Image: 'hystax/bi_scheduler:2024111501-public'>, 'booking_observer': <Image: 'hystax/booking_observer:2024111501-public'>, 'bulldozer_api': <Image: 'hystax/bulldozer_api:2024111501-public'>, 'bulldozer_worker': <Image: 'hystax/bulldozer_worker:2024111501-public'>, 'bumischeduler': <Image: 'hystax/bumischeduler:2024111501-public'>, 'bumiworker': <Image: 'hystax/bumiworker:2024111501-public'>, 'calendar_observer': <Image: 'hystax/calendar_observer:2024111501-public'>, 'cleanelkdb': <Image: 'hystax/cleanelkdb:2024111501-public'>, 'cleaninfluxdb': <Image: 'hystax/cleaninfluxdb:2024111501-public'>, 'cleanmongodb': <Image: 'hystax/cleanmongodb:2024111501-public'>, 'configurator': <Image: 'hystax/configurator:2024111501-public'>, 'demo_org_cleanup': <Image: 'hystax/demo_org_cleanup:2024111501-public'>, 'diproxy': <Image: 'hystax/diproxy:2024111501-public'>, 'diworker': <Image: 'hystax/diworker:2024111501-public'>, 'elk': <Image: 'hystax/elk:2024111501-public'>, 'error_pages': <Image: 'hystax/error_pages:2024111501-public'>, 'etcd': <Image: 'hystax/etcd:2024111501-public'>, 'failed_imports_dataset_generator': <Image: 'hystax/failed_imports_dataset_generator:2024111501-public'>, 'grafana': <Image: 'hystax/grafana:2024111501-public'>, 'grafana_nginx': <Image: 'hystax/grafana_nginx:2024111501-public'>, 'herald': <Image: 'hystax/herald:2024111501-public'>, 'herald_executor': <Image: 'hystax/herald_executor:2024111501-public'>, 'influxdb': <Image: 'hystax/influxdb:2024111501-public'>, 'insider_api': <Image: 'hystax/insider_api:2024111501-public'>, 'insider_scheduler': <Image: 'hystax/insider_scheduler:2024111501-public'>, 'insider_worker': <Image: 'hystax/insider_worker:2024111501-public'>, 'jira_bus': <Image: 'hystax/jira_bus:2024111501-public'>, 'jira_ui': <Image: 'hystax/jira_ui:2024111501-public'>, 'katara_service': <Image: 'hystax/katara_service:2024111501-public'>, 'katara_worker': <Image: 'hystax/katara_worker:2024111501-public'>, 'keeper': <Image: 'hystax/keeper:2024111501-public'>, 'keeper_executor': <Image: 'hystax/keeper_executor:2024111501-public'>, 'live_demo_generator': <Image: 'hystax/live_demo_generator:2024111501-public'>, 'mariadb': <Image: 'hystax/mariadb:2024111501-public'>, 'metroculus_api': <Image: 'hystax/metroculus_api:2024111501-public'>, 'metroculus_scheduler': <Image: 'hystax/metroculus_scheduler:2024111501-public'>, 'metroculus_worker': <Image: 'hystax/metroculus_worker:2024111501-public'>, 'mongo': <Image: 'hystax/mongo:2024111501-public'>, 'ngui': <Image: 'hystax/ngui:2024111501-public'>, 'ohsu': <Image: 'hystax/ohsu:2024111501-public'>, 'organization_violations': <Image: 'hystax/organization_violations:2024111501-public'>, 'pharos_receiver': <Image: 'hystax/pharos_receiver:2024111501-public'>, 'pharos_worker': <Image: 'hystax/pharos_worker:2024111501-public'>, 'redis': <Image: 'hystax/redis:2024111501-public'>, 'resource_discovery': <Image: 'hystax/resource_discovery:2024111501-public'>, 'resource_observer': <Image: 'hystax/resource_observer:2024111501-public'>, 'resource_violations': <Image: 'hystax/resource_violations:2024111501-public'>, 'rest_api': <Image: 'hystax/rest_api:2024111501-public'>, 'risp_scheduler': <Image: 'hystax/risp_scheduler:2024111501-public'>, 'risp_worker': <Image: 'hystax/risp_worker:2024111501-public'>, 'slacker': <Image: 'hystax/slacker:2024111501-public'>, 'slacker_executor': <Image: 'hystax/slacker_executor:2024111501-public'>, 'trapper_scheduler': <Image: 'hystax/trapper_scheduler:2024111501-public'>, 'trapper_worker': <Image: 'hystax/trapper_worker:2024111501-public'>, 'users_dataset_generator': <Image: 'hystax/users_dataset_generator:2024111501-public'>, 'webhook_executor': <Image: 'hystax/webhook_executor:2024111501-public'>, 'gemini_scheduler': <Image: 'hystax/gemini_scheduler:2024111501-public'>, 'gemini_worker': <Image: 'hystax/gemini_worker:2024111501-public'>, 'power_schedule': <Image: 'hystax/power_schedule:2024111501-public'>, 'layout_cleaner': <Image: 'hystax/layout_cleaner:2024111501-public'>}
05:41:24.812: Tagging <Image: 'hystax/arcee:2024111501-public'> as arcee:local
Traceback (most recent call last):
  File "/home/ubuntu/optscale/optscale-deploy/venv/lib/python3.9/site-packages/docker/api/client.py", line 223, in _raise_for_status
    response.raise_for_status()
  File "/home/ubuntu/optscale/optscale-deploy/venv/lib/python3.9/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://172.31.8.117:2376/v1.35/images/sha256:0bbdc941af781438069011e5833a7639ca64c37d4bad178a65ff5a901b1a6e1b/tag?tag=local&repo=arcee&force=0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/optscale/optscale-deploy/./runkube.py", line 457, in <module>
    acr.start(args.check, args.update_only)
  File "/home/ubuntu/optscale/optscale-deploy/./runkube.py", line 335, in start
    self.tag_images_local(images)
  File "/home/ubuntu/optscale/optscale-deploy/./runkube.py", line 180, in tag_images_local
    image.tag(repository=image_name, tag=LOCAL_TAG)
  File "/home/ubuntu/optscale/optscale-deploy/venv/lib/python3.9/site-packages/docker/models/images.py", line 99, in tag
    return self.client.api.tag(self.id, repository, tag=tag, **kwargs)
  File "/home/ubuntu/optscale/optscale-deploy/venv/lib/python3.9/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/home/ubuntu/optscale/optscale-deploy/venv/lib/python3.9/site-packages/docker/api/image.py", line 507, in tag
    self._raise_for_status(res)
  File "/home/ubuntu/optscale/optscale-deploy/venv/lib/python3.9/site-packages/docker/api/client.py", line 225, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/home/ubuntu/optscale/optscale-deploy/venv/lib/python3.9/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.ImageNotFound: 404 Client Error: Not Found ("No such image: sha256:0bbdc941af781438069011e5833a7639ca64c37d4bad178a65ff5a901b1a6e1b")

**Comment by stanfra** [comment]
@suren11111, please provide command ` docker images | grep arcee` output

**Comment by surendra-tanwar** [comment]
@stanfra The output of the docker images | grep arcee command is empty because the arcee image has not been built yet. This matches the output i provided you earlier.

**Comment by stanfra** [comment]
@suren11111, runkube pulls images from Docker Hub so if runkube start tagging images it means that all images are pulled, you can build images by yourself using commands:
go to optscale repo and execute: `git checkout 2024111501-public` to checkout on release branch and start `./build.sh`
After that execute `docker images` , you should see all components from https://github.com/hystax/optscale/blob/integration/optscale-deploy/components.yaml tagged as local, then start runkube with --no-pull flag and "local" as verison.

**Comment by surendra-tanwar** [comment]
now optscale working fine. thanks
