### ISSUE TITLE
Support for Multiple GCP Projects in OptScale

### ISSUE THREAD

**Issue by GiovanniYuriMita** [hystax/optscale#466]
**Description:**
I connected OptScale to my GCP account expecting it to discover all resources and billing data across my account. However, I noticed that the integration is project-scoped. This presents a challenge since I have numerous projects and manually adding data sources for each one would be highly impractical.

I came across a related issue ([#194](https://github.com/hystax/optscale/issues/194)) where it was suggested to add data sources for every project. However, this approach seems inefficient as it would not only be overwhelming to manage but might also stress OptScale's processing, with duplicate billing exports being processed for every check.

**Request:**
Is there a way to integrate my entire GCP account into OptScale seamlessly, without having to add each project individually? If not, are there plans to implement account-wide integration for GCP? This would significantly enhance usability for organizations with multiple projects.

**Comment by stanfra** [comment]
Hi @GiovanniYuriMita, , implementation multi-project support for GCP data sources already in progress, we will add this functional into nearest releases.

**Comment by GiovanniYuriMita** [comment]
Hi @stanfra,

It’s great to hear that you’re already working on this! Do you have an estimated timeline for the release?

It would be really helpful if you could mention this issue once the release is available. In the meantime, feel free to close this issue.

Thank you so much for your efforts!

**Comment by stanfra** [comment]
Hi @GiovanniYuriMita, we implemented ability to connect GCP multiple project in one connection in release: https://github.com/hystax/optscale/releases/tag/2024122501-public

To connect GCP tenant you should perform next steps:

- Create role with provided permission on your organization level (https://hystax.com/documentation/optscale/e2e_guides/e2e_gcp.html#prepare-a-role-for-optscale) 
- Create service account(https://hystax.com/documentation/optscale/e2e_guides/e2e_gcp.html#create-service-account) 
-  **For each project needed to be added into tenant** go to "IAM & Admin" section into Google Cloud console, select IAM, and press "GRANT ACCESS" button.
-  Add created service account and assign created role to it
-  Generate API key for service account: https://hystax.com/documentation/optscale/e2e_guides/e2e_gcp.html#generate-api-key-for-your-service-account 
-  Connect Data source in OptScale using "Google Cloud Tenant"
