### ISSUE TITLE
wants to know what username and password should use to login inside kibana dashboard

### ISSUE THREAD

**Issue by prabal03-cyberoisystems** [hystax/optscale#47]
![image](https://github.com/hystax/optscale/assets/125114202/aafb9db1-2811-474f-881b-9938deca9503)

**Comment by prabal03-cyberoisystems** [comment]
I have deployed the optscale sucessfully now when I want to see the logs of the pod it is storing the pods logs in logstash so when I am accessing kibana dashboard on 30081 it is asking for username and password so what username and password should I use to login inside it

**Comment by tguisep** [comment]
https://github.com/hystax/optscale/issues/23

Take note: I bypassed the login system, but on my side, the services is empty (no logs)

**Comment by nexusriot** [comment]
you can change login credentials [here](https://github.com/hystax/optscale/blob/integration/docker_images/grafana_nginx/htpasswd)

according to the missing logs please check ```/etc/docker/daemon.json ``` should be valid ip there
```
{
  "storage-driver": "overlay2",
  "log-driver": "gelf",
  "log-opts": {
    "gelf-address": "udp://192.168.88.35:12201"
  }
}
```
then restart docker service
```
sudo systemctl daemon-reload
```
```
sudo service docker restart
```
