### ISSUE TITLE
Facing issue in SMTP integration 

### ISSUE THREAD

**Issue by girish-habile** [hystax/optscale#474]
I want to integrate email services into my OptScale server. To do this, I followed the Configration change  below, but I am facing some issues:

service_credentials:
  aws:
    access_key_id: accesskeyid
    secret_access_key: secretaccesskey
  azure:
    client_id: clientid
    tenant: tenant
    secret: secret
    subscription_id: subscriptionid
  alibaba:
    access_key_id: accesskeyid
    secret_access_key: secretaccesskey
  gcp:
    credentials:
      type: service_account
      project_id: yourprojectid
      private_key_id: yourprivatekeyid
      private_key: |
        -----BEGIN PRIVATE KEY-----
        -----END PRIVATE KEY-----
      client_email: optscale-service-credentials@yourproject.iam.gserviceaccount.com
      client_id: "111111111"
      auth_uri: https://accounts.google.com/o/oauth2/auth
      token_uri: https://oauth2.googleapis.com/token
      auth_provider_x509_cert_url: https://www.googleapis.com/oauth2/v1/certs
      client_x509_cert_url: >-
        https://www.googleapis.com/robot/v1/metadata/x509/optscale-service- 
         credentials%40yourproject.iam.gserviceaccount.com
    
    pricing_data:
      dataset_name: pricing_dataset
      table_name: cloud_pricing_export
    project_id: yourprojectid

# SMTP server and credentials used for sending emails
smtp:
  server: email.com  # SMTP server address
  email: no-reply@gmai.com               # Sender email address
  login: addhydohhgdgy                 # SMTP login username
  port: 587                                     # Port for STARTTLS
  password: DHUDVJFKOYEVJG  # SMTP password
  protocol: TLS                               # Secure connection protocol

google_calendar_service:
  access_key:
    type: service_account
    project_id: optscale
    private_key_id: eeee000
    private_key: |
      -----BEGIN PRIVATE KEY-----
      -----END PRIVATE KEY-----
    client_email: calendar-service@optscale.iam.gserviceaccount.com
    client_id: ""
    auth_uri: https://accounts.google.com/o/oauth2/auth
    token_uri: https://oauth2.googleapis.com/token
    auth_provider_x509_cert_url: https://www.googleapis.com/oauth2/v1/certs
    client_x509_cert_url: https://www.googleapis.com/robot/v1/metadata/x509/calendar-service@optscale.iam.gserviceaccount.com

encryption_key: fffffxdddeadb33f

auth:
  google_oauth_client_id: ""
  google_oauth_client_secret: ""
  microsoft_oauth_client_id: ""

ngui:
  env:
    build_mode: ""
    google_oauth_client_id: ""
    microsoft_oauth_client_id: ""
    google_map_api_key: ""
    ganalytics_id: ""
    hotjar_id: ""

elk:
  env:
    htpasswd_user: userforelk
    htpasswd_pass: passwordforelk

grafana:
  env:
    htpasswd_user: userforgrafana
    htpasswd_pass: passwordforgr

In this YAML file, I added my SMTP credentials, but I encountered the following error:
**Error: failed to parse overlay/user_template.yml: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go value of type map[string]interface {}**

**Comment by stanfra** [comment]
Hi @girish-habile, looks like your user_template.yml can not be parsed. Please check that your user_template.yml follows YAML syntax. Pay special attention to spaces usage and try to use yaml validator to check that your yml file is not broken.
