### ISSUE TITLE
Version upgrade for tools used in project

### ISSUE THREAD

**Issue by saileshsp** [hystax/optscale#476]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/SAILES~1.SEE/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/SAILES~1.SEE/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#467886" vlink="#96607D">

Software | Version | Purpose | End of Support
-- | -- | -- | --
Docker | 19.03 | Containerization | 8/1/2021
Kubernetes | 1.17.3 | Automate   the deployment, scaling, and management of containerized applications | 13/1/2021
Helm | 2.17.0 | Kubernetes   package manager | 28/11/2020
Python | 3.9.16 | Programming   language | 31/10/2025
Tornado | 6.3.3 | Framework   used | NA
MariaDB | 10.3 | Database   management system | 25/5/2023
MongoDB | 3.6 | NoSQL   database | 30/4/2021
Redis | 7.0.9 | In-memory   data structure store | 29/7/2024
ELK | 7.16.2 | Logging   and analytics | NA
etcd | 3.2.13 | Key-value   store for distributed systems | 28/3/2021
Grafana | 8.2.1 | Data   visualization and monitoring | 9/6/2023
Nginx | 1.17.1 | Web   server and reverse proxy | 20/4/2021
InfluxDB | 1.3.1 | Time-series   database | 2/11/2022
Apache Spark | 3.3.0 | Cluster-computing   framework | 9/12/2023
Ubuntu | 20.04 | Operating   system | 2/4/2030

</body>

</html>

as most of tools used reached EOL is there a plan for upgrade activity in the main branch

**Comment by stanfra** [comment]
Hi @saileshsp, we have a plan to upgrade tools in december-january. Information about this will be indicated in the upcoming releases release notes.
