### ISSUE TITLE
Google's Resource view is broken?

### ISSUE THREAD

**Issue by efbe2121** [hystax/optscale#49]
When i tried to view Resource tab, it goes like this.
Tried on other installation, also provide same view.

Currency : IDR
Env : AWS Ec2

![image](https://github.com/hystax/optscale/assets/44221453/0263f87b-56b3-4658-9455-d4688261eedd)

**Comment by maxb-hystax** [comment]
Hi! Can you provide more datails? Which exact page is failing? Part of URL would help us to locate it.

**Comment by efbe2121** [comment]
> Hi! Can you provide more datails? Which exact page is failing? Part of URL would help us to locate it.

So i installed Hystax Optscale on EC2 (AWS) with the Ansible Command like weeks ago. everything was working well.
Just now i noticed the link https://xxxxx/resources doesn't work and keep showing "Something Went Wrong!"

Weirdest part is, it only happen on my Google's Data Source which has IDR Currency. 
I tried on my AWS's Data Source which has USD Currency, everything works fine.

**Comment by efbe2121** [comment]
fyi, the default full path after i access the /resources is
https://xxxxxx/resources?breakdownBy=expenses&dailyExpensesBreakdownBy=service_name

**Comment by maxb-hystax** [comment]
Thanks! Let us check it on our side.

**Comment by efbe2121** [comment]
> Thanks! Let us check it on our side.

Is there any new follow up ?

**Comment by efbe2121** [comment]
@maxb-hystax Maybe if this could narrow down your troubleshooting, 
when i tried to filter the data by using Compute Engine & Volume (check image), the view got broken. But if i try to view other services, it works fine
![image](https://github.com/hystax/optscale/assets/44221453/55effd7c-94b6-47a2-87d0-8b56337166e9)

When loading :
![image](https://github.com/hystax/optscale/assets/44221453/508fe3b0-85e0-4960-bd59-90ac610e0cd4)
After loading :
![image](https://github.com/hystax/optscale/assets/44221453/4df6addf-6f24-4a2e-bc1f-f1c6e056356c)

PATH : /resources/?breakdownBy=expenses&dailyExpensesBreakdownBy=service_name&resourceCountBreakdownBy=resource_type&resourceType=Volume%3Aregular&serviceName=Compute%20Engine


< Update >
After troubleshooting myself by analyzing the Responses Payload, i found out that, if the volume tags contains Null Value, it will somehow break.

**Comment by maxb-hystax** [comment]
Hi @efbe2121! Thank you for the detailed report! 
I'm confirmed the issue with the development team, and we got fix for it.
The fix will be published approx. next week, along with many other updates, as we are now setting up pipelines to streamline our work in private repo to the public one.

**Comment by maxb-hystax** [comment]
@efbe2121 Can you please check if you can reproduce this now on the newest version?

**Comment by efbe2121** [comment]
> @efbe2121 Can you please check if you can reproduce this now on the newest version?

Yes it's already fixed
