### ISSUE TITLE
MAIL FROM: Missing in Email Template for New Demo User Notifications

### ISSUE THREAD

**Issue by siddi0812** [hystax/optscale#492]
When a new user registers for a demo, the notification email sent to the admin is missing the "FROM:" field in the email header. As a result, the email is sent without a visible sender address. It appears that the email template for these notifications does not properly configure the "FROM:" value.

Please see the screenshot

![Screenshot 2024-12-11 170322](https://github.com/user-attachments/assets/4b0eaa08-fac3-4ed3-b676-65622c830105)

Other notification emails work without any issues, so this seems to be specific to the demo registration email template.
We use the last version from optscale

**Comment by stanfra** [comment]
Hi @siddi0812, please attach logs of herald service when problem email sent to help us investigate the problem. How to connect to kibana: https://hystax.com/documentation/optscale/private_deployments/kibana_logs.html . To find logs in kibana please use message `container_name: *herald*` in search.

**Comment by siddi0812** [comment]
Of course. I'm not quite up to speed with Elasticsearch yet, but I hope you can do something with it:

INFO:herald.herald_server.processors.main:processing new email task {'email': ['mail-sender@mail-sender.de'], 'subject': '[demo.demplatform.de] New live demo subscriber', 'template_type': 'new_subscriber', 'template_params': {'texts': {'user': {'email': 'mailrecipient@mailrecipient.de', 'subscribe': True}}}, 'reply_to_email': 'mailrecipient@mailrecipient.de'}

This actually looks really good, but even from this test I see a problem with the incoming mail:

Content-Type: multipart/related; boundary="===============6504610216632383972=="
MIME-Version: 1.0
Subject: [demo.demplatform.de] New live demo subscriber
To: mailrecipient@mailrecipient.de
reply-to: mail-sender@mail-sender.de
X-SM-incoming: yes
X-Passed: F767F806B5D7BC1AC03C33503EBB4A0890FB73D19A73D80013EE3D48382B5CB4
Message-ID:
 <addad455-8515-411f-b59c-4e02d700799b@DB1PEPF000509FA.eurprd03.prod.outlook.com>
Return-Path: smtp@smtpdomain.de
Date: Thu, 12 Dec 2024 12:09:13 +0000
X-MS-Exchange-Organization-ExpirationStartTime: 12 Dec 2024 12:09:13.7668
 (UTC)

**Comment by stanfra** [comment]
@siddi0812, please attach all sending email herald logs, you attached only task body.

**Comment by siddi0812** [comment]
Ah moment, here is the csv log.

[Untitled discover search.csv](https://github.com/user-attachments/files/18112111/Untitled.discover.search.csv)

**Comment by stanfra** [comment]
@siddi0812 , we can't reproduce your problem on our deployments, we get "New subscriber" email with "From" correctly. I can suggest making changes to the file `herald/modules/email_sender/sender.py` and add `message['From'] = email` into line 24:
![1](https://github.com/user-attachments/assets/49202a71-2ee9-4182-bba5-b66c0ae7ad54)

Then rebuild herald images using `./build.sh herald` from optscale repo and then delete all herald pods to  restart them

**Comment by siddi0812** [comment]
Hi,

i found the problem in the herald/modules/email_generator/generator.py
This line was missing:

    msg['From'] = frm


![image](https://github.com/user-attachments/assets/62fd963c-67a6-4b89-b26a-fac6dbfbb303)

You also have to change the e-mail address, otherwise the e-mail will always be rated as spam or will not arrive at all.

**Comment by sd-hystax** [comment]
Hello @siddi0812 
We specifically removed the 'From' from the body of the email. Now we use the `from_addr` parameter in smtp_server.sendmail function (sender.py, lines 52, 59). This parameter value stored in etcd `/smpt/email`

**Comment by sd-hystax** [comment]
I think you should check your smtp settings first: 
Go to etcd and check value is set: `/smtp/email`
