### ISSUE TITLE
how to Remove the Signin buttons ?

### ISSUE THREAD

**Issue by surendra-tanwar** [hystax/optscale#497]
![Screenshot from 2024-12-16 17-19-39](https://github.com/user-attachments/assets/5eacacbb-1c6d-4184-ae9c-3c5874931b0b)

In the above image, I want to remove the "Sign in with Google" and "Sign in with Microsoft" buttons. I updated the code to remove these buttons and then ran the following command:  
./runkube.py --with-elk --update-only --optscale-deployment-name <latest>  
However, this did not reflect the changes. Could you guide me on how to properly apply these changes?

**Comment by ek-hystax** [comment]
Hi @surendra-ta 👋,

To update the ngui component, you need to rebuild its Docker image and restart the corresponding pod to apply the changes.

### Steps to Update ngui:
1. Make the necessary changes in the ngui project.

2. Navigate to the root directory of the optscale repository:
```
> cd optscale
```
3. Rebuild the Docker image and restart the ngui pod:
You can either build the image manually or use the build.sh script:

**Option 1**: Manual build:
```
> docker build -t ngui:local -f ngui/Dockerfile . && kubectl delete pod $(kubectl get pod | awk '/ngui/ {print $1}')
```
**Option 2**: Use the build.sh script:
```
> ./build.sh ngui
> kubectl delete pod $(kubectl get pod | awk '/ngui/ {print $1}')
```

4. [Optional] Verify that the ngui pod has restarted:
```
> kubectl get pods | grep ngui
```
Example output:
```
NAME                                READY   STATUS    RESTARTS      AGE
ngui-866795d6c5-nfhkw               1/1     Running   0          -->33s
````

Let me know if this resolves your issue! 😊

**Comment by siddi0812** [comment]
You must adapt the template: ngui/ui/src/components/OAuthSignIn/OAuthSignIn.tsx.

It is best to comment out the area:


`const OAuthSignIn = ({ googleButton, microsoftButton }) => (
  <Grid container alignItems="center" justifyContent="center" spacing={SPACING_1}>
    <Grid item xs={12}>
      <SubTitle>
        <FormattedMessage id="signInWith" />
      </SubTitle>
    </Grid>
    {/* <Grid item xs={6}>
      {googleButton}
    </Grid>
    <Grid item xs={6}>
      {microsoftButton}
    </Grid> */}
  </Grid>
);`

Then carry out the steps as described by @ek-hystax

**Comment by surendra-tanwar** [comment]
thanks its working @ek-hystax  @siddi0812
