### ISSUE TITLE
Google Cloud billing report attempt failed. 

### ISSUE THREAD

**Issue by ryansk** [hystax/optscale#50]
I spun up an Ubuntu 20.04.6 LTS machine in AWS and followed setup documentation [found here](https://github.com/hystax/optscale/blob/integration/optscale-deploy/README.md). The cluster comes up without issue.

Following the documentation [found here](https://hystax.com/documentation/optscale/e2e_guides/e2e_gcp.html), however, after setting up credentials, I receive:

Object name : GCP Organization
Object type : report_import 
Description : Billing data import for cloud account GCP Organization (#####################) failed: 'NoneType' object has no attribute 'lower'

**Comment by efbe2121** [comment]
Up

Is this the same reason as my Issue?
https://github.com/hystax/optscale/issues/49

**Comment by maxb-hystax** [comment]
Hi! No, I don't think that #49 is the same one. Your issue looks related to the processing of billing data in diworker service. We're checking the code to find out what's going on there.

**Comment by maxb-hystax** [comment]
Please check on this release, should be fixed - https://github.com/hystax/optscale/releases/tag/2023092001-public

**Comment by Shikhar-Nahar** [comment]
Similar issue is happening again in `2024080501-public` -> https://github.com/hystax/optscale/issues/368
