### ISSUE TITLE
Did not getting user invites

### ISSUE THREAD

**Issue by hamzamaan** [hystax/optscale#51]
Hi @maxb-hystax  @sd-hystax @nexusriot @tguisep ,

I have configured Postfix SMTP on Ubuntu Linux OS  and added SMTP configuration details in user-template.yaml.  But It is not working. Anyone here can help me to solve this issue ASAP.

**Comment by hamzamaan** [comment]
Kindly help in this issue. @nexusriot @maxb-hystax @sd-hystax @tguisep

**Comment by hamzamaan** [comment]
@nexusriot @maxb-hystax @sd-hystax @tguisep  

Soft Reminder!
Kindly help in this issue.

**Comment by maxb-hystax** [comment]
Hi @hamzamaan!
Did you check the logs of Herald service (this is the service which actually sends the emails). You can filter them in Kibana with query like `container_name:*herald*`
