### ISSUE TITLE
Unable to troubleshoot initial-config-nginx-ingress-controller-2pcrl and JiraBus Pods

### ISSUE THREAD

**Issue by hamzamaan** [hystax/optscale#52]
![image](https://github.com/hystax/optscale/assets/41535104/0566a223-13eb-4ec0-9b85-cc8022685a36)

Hi @nexusriot @maxb-hystax @sd-hystax @tguisep @hx-nick

I am facing this issue. I have attached the error. Kindly help!

**Comment by hamzamaan** [comment]
@nexusriot @maxb-hystax @sd-hystax @tguisep

Soft Reminder!
Kindly help in this issue.

**Comment by nexusriot** [comment]
you can use **elk/kibana** to diagnose the problem

1. can be accessed on http://<server_ip>:30081
2. kibana password can be changed [here](https://github.com/hystax/optscale/blob/integration/docker_images/elk/htpasswd), do not forget to rebuild after changing
3. then login to kibana using credentials from step 2, create search pattern ```*, @timestamp ```
4. use following request to find logs
![image](https://github.com/hystax/optscale/assets/1822152/131925cd-f4b5-4139-97b3-4d21096d725e)
