### ISSUE TITLE
unauthorized request send to servers

### ISSUE THREAD

**Issue by Monika-didwania** [hystax/optscale#60]
I deployed optscale on my server using it's git repository in this process it send unauthorized request to other anonymous servers. I tried two times both time i get IT regulation mail regarding security breach.
How can i solve this. And can i get a demo of how to attach aws root user as it doesn't take root acoount.

**Comment by maxb-hystax** [comment]
Hi Monika,

Can you please list the servers it tries to connect? The code doesn't connect to any Hystax servers, so we think it might be some third party components. This information would greatly help us to identify and eliminate such behaviour.

**Comment by Monika-didwania** [comment]
this is the email i got from AWS when i deploy optscale on ec2 instance.

We've received a report(s) that your AWS resource(s)

AWS ID: 188435225115    Region: us-east-2    EC2 Instance Id: i-0d3fb940f00add9a9
AWS ID: 188435225115    Region: us-east-2    Network Interface Id: eni-0a3866fa22b234513


has been implicated in activity which resembles scanning remote hosts on the internet for security vulnerabilities. Activity of this nature is forbidden in the AWS Acceptable Use Policy (https://aws.amazon.com/aup/). We've included the original report below for your review. We are aware that your instance is in a stopped state, it will not be able to disrupt other resources. This step does not resolve this abuse case.

Please be aware that restarting this instance may allow the abusive activity to continue. AWS requires the instance to be terminated or that you provide a detailed explanation of how you resolved the underlying issue in order to prevent additional abuse.

**Comment by maxb-hystax** [comment]
Hi Monika,

Please redeploy OptScale on a fresh instance which has SG that denies access to SSH port tcp/22 for all IPs except your own.
