### ISSUE TITLE
Update / Migration

### ISSUE THREAD

**Issue by tguisep** [hystax/optscale#63]
Hello,

I'm running a previous version of OPTSCALE.

I'm interested about the last changes (specifically the BI module !), but the number of changes look very high.

**So, I have two possibilities:**
- Try a upgrade of the current one (after backup)
- Install a new version, running aside of the current one, integrate my parameters ( I made automation script to integrate everything quickly, I ll try too clean them and share it )

What do you suggest ?

Are you planning new massive update in the coming month ? ( It may be interesting to wait little bit in this case)

Anyway, good work !

Thomas.

**Comment by maxb-hystax** [comment]
Hi Thomas!

You can try with the update, should not be an issue. Your feedback will be much appreciated.

Re further updates - starting from now, we are actively transitioning the GitHub, so code updates will be more frequent and much smaller. Image updates will be bi-weekly with manual build for the next 4-6 weeks, while we will be working on build pipelines. After that, images will be automatically updated and correlated with our SaaS updates.

**Comment by tguisep** [comment]
I tried twice, but the pod ngui do not start;

```bash
ubuntu@ip-10-130-1-3:/opt/optscale/optscale-deploy$ kubectl get pods |grep ngui
ngui-5d9c5886b5-77f77                                           0/1     CrashLoopBackOff   7          16m

Events:
  Type     Reason            Age                   From                    Message
  ----     ------            ----                  ----                    -------
  Warning  FailedScheduling  18m (x4 over 18m)     default-scheduler       0/1 nodes are available: 1 Insufficient pods.
  Normal   Scheduled         18m                   default-scheduler       Successfully assigned default/ngui-5d9c5886b5-77f77 to ip-10-130-1-3
  Normal   Pulled            18m                   kubelet, ip-10-130-1-3  Container image "busybox:local" already present on machine
  Normal   Started           18m                   kubelet, ip-10-130-1-3  Started container wait-auth
  Normal   Created           18m                   kubelet, ip-10-130-1-3  Created container wait-auth
  Normal   Created           18m                   kubelet, ip-10-130-1-3  Created container wait-restapi
  Normal   Pulled            18m                   kubelet, ip-10-130-1-3  Container image "busybox:local" already present on machine
  Normal   Started           18m                   kubelet, ip-10-130-1-3  Started container wait-restapi
  Normal   Started           18m                   kubelet, ip-10-130-1-3  Started container wait-keeper
  Normal   Pulled            18m                   kubelet, ip-10-130-1-3  Container image "busybox:local" already present on machine
  Normal   Created           18m                   kubelet, ip-10-130-1-3  Created container wait-keeper
  Normal   Pulled            18m                   kubelet, ip-10-130-1-3  Container image "busybox:local" already present on machine
  Normal   Created           18m                   kubelet, ip-10-130-1-3  Created container wait-slacker
  Normal   Started           18m                   kubelet, ip-10-130-1-3  Started container wait-slacker
  Normal   Pulled            16m (x3 over 16m)     kubelet, ip-10-130-1-3  Container image "ngui:local" already present on machine
  Normal   Created           16m (x3 over 16m)     kubelet, ip-10-130-1-3  Created container ngui
  Normal   Started           16m (x3 over 16m)     kubelet, ip-10-130-1-3  Started container ngui
  Warning  BackOff           3m30s (x61 over 16m)  kubelet, ip-10-130-1-3  Back-off restarting failed container
```

**Comment by maxb-hystax** [comment]
Can you check that you didn't hit the limit on pods count on the node?
Current limit is *MaxPods* in `/var/lib/kubelet/config.yaml` on node host.

**Comment by tguisep** [comment]
Hello,

I checked, no issue on that point.

**- Found issue 01:**
https://github.com/hystax/optscale/blob/integration/ngui/server/server.ts#L102

UI_BUILD_PATH is missing and generate a error
I added naively the env as in : https://github.com/hystax/optscale/blob/integration/optscale-deploy/optscale/templates/ngui.yaml#L58
```
        - name: UI_BUILD_PATH
          value: ""
```
Well, the ngui app do not start properly, but the pod start.

**- Found issue 02:**
Regarding:
https://github.com/hystax/optscale/blob/integration/ngui/Dockerfile#L36
and
https://github.com/hystax/optscale/blob/integration/ngui/server/server.ts#L110

We should expect a internal port as 4000
But it's defined as 9999 in:
https://github.com/hystax/optscale/blob/integration/optscale-deploy/optscale/values.yaml#L240

So, the probe is failing.

**Comment by tguisep** [comment]
Finally, with
`value: "/usr/src/app/ui/"`

The app start properly, but the auth service is broken.
Digging
`/auth/v2/tokens: Internal Server Error`

**Comment by maxb-hystax** [comment]
Thanks for diagnostics! Reproducing it from our end as well.

**Comment by tguisep** [comment]
The issue with auth come from the change in : 
https://github.com/hystax/optscale/blob/cc526f13e111a2a53796aa7c601495a63d0fdd07/auth/auth_server/utils.py#L81

Introducing a new key etcd  "encryption_salt_auth" in place of  "encryption_auth".

This change would be managed by:
https://github.com/hystax/optscale/blob/integration/deploy/docker_images/configurator/configurator.py#L107C32-L107C32

By on my side, the key has not been created in the etcd server.

I added manually with the value of "encryption_auth"  , it works.

**Comment by maxb-hystax** [comment]
Thanks Thomas!
