### ISSUE TITLE
SSO Google: GOOGLE_OAUTH_CLIENT_SECRET not documented

### ISSUE THREAD

**Issue by tguisep** [hystax/optscale#65]
Hello,

env var GOOGLE_OAUTH_CLIENT_SECRET in auth module to use SSO Google is required, but not documented.

https://github.com/hystax/optscale/blob/cc526f13e111a2a53796aa7c601495a63d0fdd07/auth/auth_server/controllers/signin.py#L44

Issue validated with in auth.yaml:
```
        - name: GOOGLE_OAUTH_CLIENT_SECRET
          value: GOCSPX-MYSECRET
```

Thomas.

**Comment by maxb-hystax** [comment]
Thanks @tguisep!
