### ISSUE TITLE
Failed to establish a new connection

### ISSUE THREAD

**Issue by nagabharat** [hystax/optscale#72]
HTTPConnectionPool(host='192.168.11.99', port=2376): Max retries exceeded with url: /v1.35/images/create?tag=2087b982dfc054c6800ab0e3c1e32bcf4e150ee1&fromImage=index.docker.io%2Fhystax%2Farcee (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f50d29fcd60>: Failed to establish a new connection: [Errno 110] Connection timed out'))

**Comment by maxb-hystax** [comment]
Please check your connectivity with dockerhub.

**Comment by nagabharat** [comment]
I was trying to deploy on aws ec2, do i need to open any port? tried to pull other dockerhub images was able to any to test to confirm the connectivity

**Comment by nagabharat** [comment]
is this the docker hub url ? index.docker.io/hystax/arcee

**Comment by nagabharat** [comment]
resolved was able solve
