### ISSUE TITLE
ri_sp_expenses_breakdown: Internal Server Error

### ISSUE THREAD

**Issue by efbe2121** [hystax/optscale#73]
Hello Hystax team,

I've installed the latest commit of Hystax in my ec2 instance, and deploy exactly using the deployment guide. With few fixes i read from the Issue Tab on optscale/templates/ngui.yaml

Whenever i open the Recommend tab on the Page, this thing pop ups almost everytime
/restapi/v2/organizations/<organization_id>/ri_sp_expenses_breakdown: Internal Server Error

**Comment by tguisep** [comment]
Hello,
Same on my side, since : https://github.com/hystax/optscale/commit/eb6f5f34f590bc800d886ffebc3f3e67695b0140
I didn't had time to dig that one .

**Comment by efbe2121** [comment]
Is there any update on fixing the error?

**Comment by maxb-hystax** [comment]
Hi! 
The fix is ready and will be published soon.

**Comment by maxb-hystax** [comment]
Hi! Please use this released version, with the fix - https://github.com/hystax/optscale/releases/tag/2023092001-public
