### ISSUE TITLE
create more than one node cluster and deploy

### ISSUE THREAD

**Issue by nagabharat** [hystax/optscale#74]
I was able to do it only for one node K8 cluster based on documentation( 
https://github.com/hystax/optscale/blob/integration/optscale-deploy/README.md ).
How to do it for more than one node?
or any way to deploy it to eks or aks for managed k8s?

**Comment by tguisep** [comment]
runkube.py is just a wrapper.

I guess if you use the option "--config" to use your k8s config file, you should be able to manage any cluster.
https://github.com/hystax/optscale/blob/integration/optscale-deploy/runkube.py#L333

Not tested on my side.

**Comment by nagabharat** [comment]
tried using "--config" for EKS, as of k8 1.24 the dockerd is deprecated and replaced with  containerd and it is unable to pull images to nodes as there is no dockerd on the nodes.

**Comment by efbe2121** [comment]
> tried using "--config" for EKS, as of k8 1.24 the dockerd is deprecated and replaced with containerd and it is unable to pull images to nodes as there is no dockerd on the nodes.

Do you find a way to workaround it?

**Comment by nagabharat** [comment]
No, not working on it now ,will start working on it next week as i am busy with few other projects.

**Comment by stanfra** [comment]
We do not support multinode deployments and deployments on EKS. If you like to implement support please make pool request and we take a look on it
