### ISSUE TITLE
Sender email incompatibility with aws SES

### ISSUE THREAD

**Issue by tguisep** [hystax/optscale#79]
Hello,

Herald service take in consideration than the sender email is the login.
But in some case like for AWS SES, it's a specific user.

eg:
```
SES_USERNAME="AK****************542"
SES_PASSWORD="MY_SES_PASSWORD"
```

https://github.com/hystax/optscale/blob/5c6038d2fb2f50b1ef8da56c78958de5fd53218a/herald/modules/email_sender/sender.py#L42

Other incompatibility:
- Login fail because SES_USERNAME format do not match email format

Thomas.

**Comment by maxb-hystax** [comment]
Most probably it is due to AWS SES incompatibility with smtplib.SMTP_SSL method.
Proposed solution is to introduce config parameter "email_mode" which will cause smth like the following in "aws_ses" mode:
```
smtp = smtplib.SMTP("email-smtp.us-east-1.amazonaws.com")
smtp.starttls()
smtp.login(SESSMTPUSERNAME, SESSMTPPASSWORD)
smtp.sendmail(me, you, msg)
```

**Comment by tguisep** [comment]
Thank for the proposal.
I ll try to implement that & build my own image.
