### ISSUE TITLE
Root Access

### ISSUE THREAD

**Issue by Upasana1000** [hystax/optscale#8]
How to get the root access in optscale?

**Comment by maxb-hystax** [comment]
If you are speaking about root access to the containers/dbs etc. - it is totally under your control, as you are in the power of the host to which you deploy it.
Speaking about UI - OptScale is designed as SaaS without superuser-level access for security reasons.

**Comment by mdevengine13** [comment]
I wish at least the mongodb user/passwd is shared. there is no way to change it in the container. mongo doesnt even the root to add/remove/update.
