### ISSUE TITLE
unable to build kubernetes objects from release manifests

### ISSUE THREAD

**Issue by saleem-unifycare** [hystax/optscale#83]
HI Team,
we are getting below error when running "./runkube.py --use-socket --with-elk -o overlay/user_template.yml -- component_versions.yaml"

Release "optscale" does not exist. Installing it now. Error: unable to build kubernetes objects from release manifest: [resource mapping not found for name: "mongo" namespace: "" from "": no matches for kind "PodDisruptionBudget" in version "policy/v1beta1" ensure CRDs are installed first, resource mapping not found for name: "rabbitmq" namespace: "" from "": no matches for kind "PodDisruptionBudget" in version "policy/v1beta1" ensure CRDs are installed first, resource mapping not found for name: "bi-scheduler" namespace: "" from "": no matches for kind "CronJob" in version "batch/v1beta1" ensure CRDs are installed first, resource mapping not found for name: "booking-observer-scheduler" namespace: "" from "": no matches for kind "CronJob" in version "batch/v1beta1" ensure CRDs are installed first, resource mapping not found for name: "calendar-observer-scheduler" namespace: "" from "": no matches for kind "CronJob" in version "batch/v1beta1" ensure CRDs are installed first, resource mapping not found for name: "cleaninfluxdb" namespace: "" from "": no matches for kind "CronJob" in version "batch/v1beta1" ensure CRDs are installed first, resource mapping not found for name: "demoorgcleanup" namespace: "" from "": no matches for kind "CronJob" in version "batch/v1beta1" ensure CRDs are installed first, resource mapping not found for name: "failed-imports-dataset-generator" namespace: "" from "": no matches for kind "CronJob" in version "batch/v1beta1" ensure CRDs are installed first, resource mapping not found for name: "insider-scheduler" namespace: "" from "": no matches for kind "CronJob" in version "batch/v1beta1" ensure CRDs are installed first, resource mapping not found for name: "metroculusscheduler" namespace: "" from "": no matches for kind "CronJob" in version "batch/v1beta1" ensure CRDs are installed first, resource mapping not found for name: "organization-violations-scheduler" namespace: "" from "": no matches for kind "CronJob" in version "batch/v1beta1" ensure CRDs are installed first, resource mapping not found for name: "report-import-scheduler-0" namespace: "" from "": no matches for kind "CronJob" in version "batch/v1beta1" ensure CRDs are installed first, resource mapping not found for name: "report-import-scheduler-1" namespace: "" from "": no matches for kind "CronJob" in version "batch/v1beta1" ensure CRDs are installed first, resource mapping not found for name: "report-import-scheduler-24" namespace: "" from "": no matches for kind "CronJob" in version "batch/v1beta1" ensure CRDs are installed first, resource mapping not found for name: "report-import-scheduler-6" namespace: "" from "": no matches for kind "CronJob" in version "batch/v1beta1" ensure CRDs are installed first, resource mapping not found for name: "resource-discovery-scheduler" namespace: "" from "": no matches for kind "CronJob" in version "batch/v1beta1" ensure CRDs are installed first, resource mapping not found for name: "resource-observer-scheduler" namespace: "" from "": no matches for kind "CronJob" in version "batch/v1beta1" ensure CRDs are installed first, resource mapping not found for name: "resource-violations-scheduler" namespace: "" from "": no matches for kind "CronJob" in version "batch/v1beta1" ensure CRDs are installed first, resource mapping not found for name: "thanos-compactor" namespace: "" from "": no matches for kind "CronJob" in version "batch/v1beta1" ensure CRDs are installed first, resource mapping not found for name: "trapper-scheduler" namespace: "" from "": no matches for kind "CronJob" in version "batch/v1beta1" ensure CRDs are installed first, resource mapping not found for name: "users-dataset-generator" namespace: "" from "": no matches for kind "CronJob" in version "batch/v1beta1" ensure CRDs are installed first, resource mapping not found for name: "acura" namespace: "default" from "": no matches for kind "Ingress" in version "extensions/v1beta1" ensure CRDs are installed first] Traceback (most recent call last): File "/home/ubuntu/optscale/optscale-deploy/./runkube.py", line 388, in <module> acr.start(args.check, args.update_only) File "/home/ubuntu/optscale/optscale-deploy/./runkube.py", line 316, in start subprocess.run(update_cmd.split(), check=True) File "/usr/lib/python3.10/subprocess.py", line 526, in run raise CalledProcessError(retcode, process.args, subprocess.CalledProcessError: Command '['helm', 'upgrade', '--install', '-f', 'tmp/base_overlay', '-f', 'overlay/user_template.yml', 'optscale', 'optscale']' returned non-zero exit status 1.

please guide us.

**Comment by saleem-unifycare** [comment]
any update on this?

**Comment by maxb-hystax** [comment]
Hi Saleem!

Can you please describe the host on which you are trying to run OptScale? Were the preparation steps described in deployment instruction successful?

**Comment by saleem-unifycare** [comment]
we are using bastion host to connect kubernetes cluster. Configuration follows as below

bastion host configuration:

`ubuntu@ip-172-31-0-207:~$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal`


Aws-eks configuration:
Instance type : c5a.2xlarge
SSD :150GB
Memory: 16GB

helm version : version.BuildInfo{Version:"v3.12.3", GitCommit:"3a31588ad33fe3b89af5a2a54ee1d25bfe6eaa5e", GitTreeState:"clean", GoVersion:"go1.20.7"}

kubectl version :
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"27+", GitVersion:"v1.27.4-eks-2d98532", GitCommit:"3d90c097c72493c2f1a9dd641e4a22d24d15be68", GitTreeState:"clean", BuildDate:"2023-07-28T16:51:44Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}


python version :
python3
Python 3.8.10 (default, May 26 2023, 14:05:08) 

preparation steps described in deployment instruction was successfull when running below command
ansible-playbook -e "ansible_ssh_user=<user>" -k -K -i "<ip address>," ansible/k8s-master.yaml

kubernetes obects are not able to find CRD's when running below command
./runkube.py --use-socket --with-elk  -o overlay/user_template.yml -- <deployment name> component_versions.yaml

**Comment by v-hx** [comment]
Hi,

Currently, the only available deployment option involves spinning up a Kubernetes cluster following the installation instructions. Please refer to the README.md file located in the root of the repository.

We have plans to extend support to other platforms and improve the deployment experience, which will require our time for investigation and implementation.

Thank you for reaching out.
